### ISSUE TITLE
版本4.1.2局域网连接的bug

### ISSUE THREAD

**Issue by luzhengyang1995** [shadowsocksr/shadowsocksr-csharp#101]
软件设置允许来自局域网的连接，代理规则设置为绕过局域网和大陆ip，然后手机上面用socks5方式连接到电脑上，发现手机所有的网页都是经过代理，并没有绕过局域网和大陆的ip
ssr版本为4.1.2

**Comment by breakwa11** [comment]
检查delegated-apnic.txt存不存在

**Comment by luzhengyang1995** [comment]
delegated-apnic.txt这个文件存在

**Comment by breakwa11** [comment]
那么检查你的DNS设置

**Comment by breakwa11** [comment]
你手机到底怎么用socks5方式的？手机的代理设置只支持http方式吧

**Comment by luzhengyang1995** [comment]
重装系统后解决这个问题，安卓手机是通过一款叫做proxydrod的软件用ROOT权限进行socks5代理

**Comment by breakwa11** [comment]
好吧
