### ISSUE TITLE
自动代理问题

### ISSUE THREAD

**Issue by stardock** [shadowsocksr/shadowsocksr-csharp#104]
我发现如果选择 Mode --> Global
IE的自动代理和手动代理都会被设置成 127.0.0.1 这样的地址。
我的理解是， 设置 成Global的时候 应该只改手动代理地址， 自动代理地址应该是不变的。 有可能设置成这样吗？

**Comment by breakwa11** [comment]
目前不支持，设置为Global的话，其它项就会清空
