### ISSUE TITLE
关于重启后配置错误

### ISSUE THREAD

**Issue by nehcnoel** [shadowsocksr/shadowsocksr-csharp#109]
你好，破娃酱。我也不知道这算不算bug，现象：关机前选中**使用域名白名单（仅http代理）**，重启之后就不再选中，屡试不爽。

我使用的翻墙配置如下：
- 系统代理模式：全局模式
- 代理规则：绕过局域网
- 服务器：使用域名白名单（仅http代理）+ssr服务器信息

是不是我所选择的配置之间有冲突呢，如有冲突，还请指正，多谢。

**Comment by breakwa11** [comment]
fixed it https://github.com/shadowsocksr/shadowsocksr-csharp/commit/9f284febfa9c458fe550fbcb4806656ea3ed84ed
