### ISSUE TITLE
总是提示下载新版本4.0.2

### ISSUE THREAD

**Issue by chakhee** [shadowsocksr/shadowsocksr-csharp#113]
尝试了最近更新的多个版本都有此问题，没有看到其他人发，所以不知是我个例还是有什么错误的配置。

**Comment by breakwa11** [comment]
那你为什么不更新？

**Comment by chakhee** [comment]
呃，我使用的都是高于4.0.2的版本，刚才尝试新出的4.1.4版本也是如此。

**Comment by breakwa11** [comment]
你确定是在我这下载的么。。。

**Comment by breakwa11** [comment]
客户端上的版本号显示呢？

**Comment by chakhee** [comment]
是的，很确定，而且用了好多版本都会这样。如果别人都没有这个问题的话，那就算了，很抱歉打扰到您。

**Comment by breakwa11** [comment]
来个客户端的服务器编辑窗口的截图

**Comment by chakhee** [comment]
![20170312212936](https://cloud.githubusercontent.com/assets/26360911/23832203/32b40d38-076b-11e7-928a-825eabe4e688.png)

点击更新提示会打开以下链接

https://github.com/shadowsocksr/shadowsocksr-csharp/releases?ShadowsocksR-win-dotnet4.0-4.0.2.7z

**Comment by breakwa11** [comment]
有更新提示之后再截图，包括菜单和这个窗口

**Comment by chakhee** [comment]
抱歉，找到原因了

**Comment by breakwa11** [comment]
@chakhee 什么原因
