### ISSUE TITLE
4.1.4 "切换系统代理模式"工作不正常

### ISSUE THREAD

**Issue by john-wang0** [shadowsocksr/shadowsocksr-csharp#115]
Step1: 切换系统代理模式为"全局模式"或者"PAC模式"
Step2: 切换回"不修改系统(IE)代理"

IE设置中的对应的勾选项没有取消.

**Comment by wenliyang** [comment]
不修改系统(IE)代理，字面意思就是“不修改”
原先打勾的，取消勾选，那叫“修改”
你应该选择“不经过代理直连”
