### ISSUE TITLE
SSR 4.1.31 "不修改系统(IE)代理"

### ISSUE THREAD

**Issue by King66** [shadowsocksr/shadowsocksr-csharp#116]
1. 从“全局模式”切换到"不修改系统(IE)代理"，IE的局域网设置的代理没有被取消。
切换到“不经过代理直连”才取消，是上面那个选项被取消了吗。。

2. 服务器-empty group- 切换服务器，但实际google IP还是没切换IP，推出重新打开SSR才切换成功。

3. 感谢作者breakwa11 !

**Comment by wenliyang** [comment]
https://github.com/shadowsocksr/shadowsocksr-csharp/issues/115

**Comment by King66** [comment]
所以就是以前的"不修改系统(IE)代理"现在被换了个名字，叫“不经过代理直连”？
感觉应该删除之前的"不修改系统(IE)代理"选项啊。

**Comment by breakwa11** [comment]
还有什么问题吗

**Comment by King66** [comment]
@breakwa11 没了，closed
