### ISSUE TITLE
建议服务器IP不要默认打码或增加控制选项

### ISSUE THREAD

**Issue by yezixi** [shadowsocksr/shadowsocksr-csharp#119]
从4.1.1版本开始服务器IP变成默认打码，对于强迫症的人（比如我）来说变的繁杂，因为每次想看看有没有节点更新，我都会对照IP自己修改，我不用一件导入，因为我还要一个个编辑节点的名字到自己觉得美观齐整为止。所以之前都只需要打开服务器列表和网站上节点及IP对照修改，现在每次还要点一下服务器IP勾选框让我感觉很难受，如果可以的话，希望能增加默认隐藏或默认显示选项，或者还是恢复默认不打码好了，因为毕竟截图不喜欢打码的人在少数，而且截图的人更在少数嘛，一般都自用。

**Comment by breakwa11** [comment]
我考虑一下解决方案

**Comment by luofengBJ** [comment]
同上~希望可以增加选项！

**Comment by Lengchenyang** [comment]
终于找到组织了  希望可以增加选项

**Comment by yezixi** [comment]
@breakwa11 希望能得到解决，辛苦了。

**Comment by TivJsou** [comment]
+1

截图打码的是少数人，决大多数人都是自用的，打码后太不方便

**Comment by SunZhizhong** [comment]
对于隐藏可以考虑单独在设置里加入选项，默认全部打开或者全部关闭。

**Comment by breakwa11** [comment]
DONE

**Comment by yezixi** [comment]
@breakwa11 解决了吗
