### ISSUE TITLE
ShadowsocksR是否支持便携化或绿色化的功能

### ISSUE THREAD

**Issue by programsuperman** [shadowsocksr/shadowsocksr-csharp#120]
原版shadowsocks具备通过在shadowsocks.exe所在的文件夹新建一个名为shadowsocks_portable的空文本文档文件来将默认保存在windows系统temp文件夹里的文件保存到shadowsocks.exe所在的文件夹里的temp文件夹里面以实现原版shadowsocks的便携化或绿色化的功能，那么请问braekwa11你的shadowsocksr是否也支持该功能，若支持的话那又该如何操作才能实现？

**Comment by breakwa11** [comment]
@programsuperman 不支持此功能，因为本来就是绿色化，不保存在系统目录

**Comment by programsuperman** [comment]
@breakwa11 谢谢您的回复。您的这句话“不支持此功能，因为本来就是绿色化，不保存在系统目录”是不是指shadowsocksr首次运行时所生成的所有文件或文件夹都是保存在shadowsocksr.exe所在的文件夹里面？如果是这样的话是不是意味着我可以将不同版本的shadowsocksr.exe程序分别存放在U盘的不同文件夹里面再分别首次运行和配置好后就可以移动式地正常使用shadowsocksr或将存放在U盘里面的不同文件夹里已经都首次运行和配置好了的任意版本的shadowsocksr.exe程序所在的文件夹复制粘贴到任意一台Win10电脑也可以在该Win10电脑上正常地使用该版本的shadowsocksr？

**Comment by breakwa11** [comment]
@programsuperman 是的，所有配置保存在同目录下，就是为了多客户端同时使用设计的

**Comment by programsuperman** [comment]
@breakwa11 great design !!! i love it !!!
