### ISSUE TITLE
建议客户端增加监测域名解析变化功能

### ISSUE THREAD

**Issue by bobo-x** [shadowsocksr/shadowsocksr-csharp#123]
应用场景：客户端中设置SSR服务器地址为某域名。运行状态时，改变了服务器IP，对应改变域名解析记录。此时客户端不能及时发现域名解析的改变，需要重启客户端才能正常使用。

建议：客户端定期监测服务器域名解析的变化，并自动重连服务器。

**Comment by breakwa11** [comment]
一年前的版本就支持你说的这个”功能“了
