### ISSUE TITLE
能否加入像SS那样的“使用远程PAC”的功能？

### ISSUE THREAD

**Issue by dxvgef** [shadowsocksr/shadowsocksr-csharp#134]
因为我Chrome里的SwitchyOmega设置的是直接使用服务端提供的远程PAC地址，修改PAC规则也是每次都在服务端的网站上修改，改了之后在SwitchyOmega里更新一下就生效了，但没法同步到SSR的本地的PAC文件里来

**Comment by katosun2** [comment]
【右键纸飞机 -> PAC -> 复制 PAC URL 】粘上去

**Comment by breakwa11** [comment]
不支持，由于客户端提供的pac内部存在动态参数，由客户端配置决定，而远程pac不支持且不安全，此功能是被删除的
