### ISSUE TITLE
无法自动生成chn_ip.txt

### ISSUE THREAD

**Issue by tengjunhui123** [shadowsocksr/shadowsocksr-csharp#139]
你好~我真正用你的SSR，最新版的4.1.5有这么一个功能：【通过自己下载delegated-apnic-latest放在同目录下并删除chn_ip.txt，会自动生成新的chn_ip.txt】，不过我试了一下，好像并没有生成新的chn_ip.txt，是我哪里做错了吗(⊙ｏ⊙)
delegated-apnic-latest是到这里下载的【http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest】，复制了全部内容粘贴到文本文档，然后保存成【delegated-apnic-latest.txt】
谢谢了喵~

**Comment by tengjunhui123** [comment]
为什么字被画横杠了(⊙ｏ⊙)

**Comment by breakwa11** [comment]
@tengjunhui123 保存为delegated-apnic-latest不要有txt后缀，不要重复问

**Comment by tengjunhui123** [comment]
好的，十分感谢~(/ω＼)
