### ISSUE TITLE
choice of ciphers is too few

### ISSUE THREAD

**Issue by testcaoy7** [shadowsocksr/shadowsocksr-csharp#14]
If I may

can you add more cipher like camellia, seed and blowfish ?

and there is a wonderful C# crypto library called Bouncy Castle, maybe you can utilize it ?

**Comment by breakwa11** [comment]
why add so many ciphers?

**Comment by testcaoy7** [comment]
well
I like to switch between ciphers because I think use one cipher for a long time is not a very good choice. My ISP at home is ChinaTelecom and I have seen some intense speed drop if I use particular cipher for several days, especially ChaCha20. 
And, Camellia is a very good cipher because it can provide the same protection level as AES and it run faster than AES in software. 
Other ciphers like seed and cast-128 is very secure as well. 
Using a vast range of cipher suites can add a lot of works to the national firewall because they cannot focus their attack on several chosen ciphers.
