### ISSUE TITLE
鼠标移到小飞机上显示当前正连接服务器...

### ISSUE THREAD

**Issue by wxlg1117** [shadowsocksr/shadowsocksr-csharp#140]
ShadowsocksR-4.1.5-win版本似乎不显示了...4.1.4版本还有的

**Comment by wxlg1117** [comment]
ShadowsocksR-4.1.5-win状态显示
![qq 20170427142910](https://cloud.githubusercontent.com/assets/9752596/25470745/47fd4aba-2b56-11e7-8375-5345a8ac292c.jpg)

ShadowsocksR-4.1.4-win状态显示
![qq 20170427143001](https://cloud.githubusercontent.com/assets/9752596/25470756/52503d42-2b56-11e7-9f9b-9405e7d23ff3.jpg)


4.1.5的状态显示当前连接服务器木有了

**Comment by breakwa11** [comment]
dup #135
