### ISSUE TITLE
4.1.5版本不如4.0稳定

### ISSUE THREAD

**Issue by magensky** [shadowsocksr/shadowsocksr-csharp#141]
我原来使用4.0版本，很稳定。
但是换过2次4.1.5后，都是使用一段时间后就是速度变慢，google也解析不出来。但是关掉重新打开4.0就一切正常了。

**Comment by breakwa11** [comment]
你这种描述我无法确定问题

**Comment by nick215441937** [comment]
这个好像不能怪SSR。。。只能怪你搞到的服务器不好
