### ISSUE TITLE
对WIN10 1703的兼容性问题

### ISSUE THREAD

**Issue by yukino521** [shadowsocksr/shadowsocksr-csharp#143]
WIN 1703无法正常使用。使用PAC模式代理后无效，仅能打开未墙网站。全局模式代理仅edge浏览器能访问被墙网站，且打开被墙网站速度非常慢，第三方浏览器依然不能访问。

**Comment by EMLVIRUS** [comment]
并未发现此问题
![image](https://cloud.githubusercontent.com/assets/16912240/25311460/1819dbbc-2834-11e7-9402-adb2c44062be.png)

**Comment by EMLVIRUS** [comment]
我错了😭确实有问题 只能使用系统代理的浏览器确实无效
我用FF手动连接127.0.0.1才能正常

**Comment by breakwa11** [comment]
win10坑太多，建议用可安装插件的浏览器代替

**Comment by dNEryno** [comment]
确实,PAC下访问网站,U2B可以,INS不行.TWITTER也可以..
浏览器插件下都没问题..也是1703系统..看来我得换系统了呀.换会WIN7

**Comment by whmjixi** [comment]
我的也是同样的问题，装了WIN10 1703新版后，就系统自带的Edge跟IE能打开被墙网站，但也是非常慢，这可怎么没办那，不想换回老系统！

**Comment by TestSmirk** [comment]
可能是公用网络和私有网络的问题. 不是有用户规则么,加入就是了

**Comment by Wows233** [comment]
用chrome啊，加个SwitchyOmega插件:https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif

**Comment by LBYPatrick** [comment]
速度慢的，国内请上混淆插件外加Google BBR算法（更换4.9或者更高内核就可以在sysctl里通过两行配置启用）（如果你不是ss服务器的搭建者那就没办法了）。只有IE和Edge的这个是因为很多应用不吃PAC，建议还是Proxifier。顺带一提，用bind9缓存一下DNS解析记录，访问部分网站有一定效果（当然，不包括Google和Youtube这样的网站）

**Comment by lifegh** [comment]
楼上各位不必沮丧，这是chrome代理不兼容新版Win10，可以安装chrome代理插件来解决这个问题！
我已上传插件SwitchyOmega离线安装包，各位可以试试：http://blog.csdn.net/qq_32115439/article/details/71995923
为了解决这个问题，昨天花了我一天一夜，实在痛苦啊。。。。

**Comment by breakwa11** [comment]
感谢楼上 @lifegh

**Comment by breakwa11** [comment]
顺便说一下，之前有网友说过另一个问题，测试后发现某win10版本保存代理设置的位置变了，所以我怀疑chrome同样是直接读取注册表方式获取的，而原本的位置是无效的
这个问题会在新版本的SSR下得到解决，但chrome的问题只能由chrome那边解决，或者安装插件

**Comment by lifegh** [comment]
微软太坑了，兼容这么大问题都乱改，只照顾亲儿子Edge和IE，前些天NSA病毒爆发，我才慌忙升级到最新版win10，结果又出现代理问题，已经被烦透了，微软吃枣药丸

**Comment by Wows233** [comment]
防病毒不需要升级win10，win7开自动更新就可以挡住。那些是未激活用户和相信“自动更新越更新越慢”的用户中招的。事实上3月就有补丁了，到现在却很多没更新的，现在才爆发
