### ISSUE TITLE
可以添加远程解析DNS的功能么？

### ISSUE THREAD

**Issue by kagurainroy** [shadowsocksr/shadowsocksr-csharp#149]
校园网有DNS污染 试了有些地址只有在sockscap64里用远程解析DNS再从里面开启chrome才能正确访问页面 但是这样灵活性很差
试着修改本地DNS和SSR选项中的DNS 以及SSR 全局代理 都失败了
可以在以后添加远程解析DNS的功能么？

**Comment by breakwa11** [comment]
这个功能可能3年多前才没有吧

**Comment by kagurainroy** [comment]
那请问这个功能怎么开启呢= =？好像设置里并没有看见
