### ISSUE TITLE
请问如何打开远程解析DNS

### ISSUE THREAD

**Issue by kagurainroy** [shadowsocksr/shadowsocksr-csharp#150]
还是说全局代理下默认走远程解析DNS?
我在选项里好像没有找到这个功能
全局代理下 访问一部分网站仍然会被DNS污染导致无法连接
如果我在sockscap64里选择远程解析域名 然后在这里面启动的话 却能正常访问

**Comment by wenliyang** [comment]
“选项设置”里，DNS设置默认为空，如果填写，就会用那个DNS来解析ssr里连接的服务器域名IP

**Comment by kagurainroy** [comment]
改了8.8.8.8、8.8.8.8:53 还有我VPS的DNS 依然无法避免DNS污染= =？比如访问斗鱼的时候被强制走IPV4 弹幕服务器连接不上 而不是通过IPV6走VPS

**Comment by csskq** [comment]
如果代理规则你选了绕过局域网和大陆，那有些域名被污染的IP地址属于大陆的话，就打不开了；然后斗鱼的弹幕是通过flash来获取的，flash是可以无视代理设置的，比如flash版speedtest即使你全局代理，它测速时连接的服务器也不走代理。

**Comment by kagurainroy** [comment]
PAC里我只绕过了172.*，192.*和127.* 而且PAC模式不行之后我试着用全局也不行 而同网站同VPS同浏览器 有其他学校的人是能正常代理的 所以我觉得应该不是FLASH问题

**Comment by csskq** [comment]
关键是代理模式和代理规则都要选全局。

**Comment by kagurainroy** [comment]
关键是系统代理模式和代理规则我都选了全局

**Comment by breakwa11** [comment]
@kagurainroy 那你为什么用sockscap64

**Comment by kagurainroy** [comment]
@breakwa11 上steam的时候用 还有一些自身没代理设置又不走系统代理的也拖进来 代理服务器填的127.0.0.1:1080

**Comment by breakwa11** [comment]
你到现在都没有说你的浏览器是什么，有没有使用插件，以及如果是firefox的话有没有开启远程DNS

**Comment by kagurainroy** [comment]
@breakwa11  浏览器是CHROME 插件是SwitchyOmega

**Comment by kagurainroy** [comment]
@breakwa11 edge也不行

**Comment by breakwa11** [comment]
@kagurainroy 别要我问一句你说一句啊，用什么插件你不顺便把配置说一下？？

**Comment by kagurainroy** [comment]
@breakwa11 
![image](https://cloud.githubusercontent.com/assets/22196444/25741250/73178e4c-31bc-11e7-8c2b-8f22e4bcce3b.png)
![image](https://cloud.githubusercontent.com/assets/22196444/25741267/81f65f2e-31bc-11e7-8d50-8731c1d1c2d6.png)
我试试直接复制能不能上传

**Comment by kagurainroy** [comment]
@breakwa11 上面一张图是PROXY1

**Comment by breakwa11** [comment]
我的天，你这样配置能连上才怪，第一图代理服务器后面三个你不能写use default吗

**Comment by ysc3839** [comment]
我来说一下我的经验：远程解析 DNS 是看应用的设置的。如果是 HTTP 代理一般会远程解析， SOCKS 代理一般不会远程解析。如 curl 的代理设置，要设置成 `socks5h://` 才会远程解析。

**Comment by kagurainroy** [comment]
@breakwa11 以前一直用的就是use default 也没连上过 改成这种试了一下 也不行 后来就没改回去了

**Comment by kagurainroy** [comment]
@breakwa11 我现在改回来use default 还是不行

**Comment by kagurainroy** [comment]
@ysc3839  “如 curl 的代理设置，要设置成 socks5h:// 才会远程解析。” 这句不太懂 可否详细说明

**Comment by ysc3839** [comment]
@kagurainroy 如果你不知道 curl 的话就忽略这句。

**Comment by breakwa11** [comment]
@kagurainroy 你不用听他的，另外你本应该把这三条回复合并在一起回复，请保证你的回复内容信息量尽可能多，不要当聊天室一次一句。麻烦你截图你的客户端的代理规则设置

**Comment by kagurainroy** [comment]
![image](https://cloud.githubusercontent.com/assets/22196444/25741428/6e38e53c-31bd-11e7-8673-55ce340417cb.png)
![image](https://cloud.githubusercontent.com/assets/22196444/25741432/73b51652-31bd-11e7-81e4-08596193a624.png)

**Comment by csskq** [comment]
你用omega扩展情况会变复杂，建议先停用扩展，让chrome使用IE的代理设置，然后代理模式和代理规则都全局看看。

**Comment by breakwa11** [comment]
请你直接使用你说的proxy1规则而不要使用自动切换规则，另外请确认你的chrome开启了远程DNS请求

**Comment by kagurainroy** [comment]
@csskq 
这个我试过 刚才为了确认又试了一遍 还是不行
@breakwa11 
直接使用proxy1规则试过 不行
 “请确认你的chrome开启了远程DNS请求” 这个没做过 请问怎么确认？

**Comment by breakwa11** [comment]
这所有的东西都与客户端无关，全是因为你自己的chrome的问题，如果你的chrome没有使用远程DNS，那么就是本地解析。你的问题请自行Google

**Comment by breakwa11** [comment]
dup #149

**Comment by breakwa11** [comment]
@kagurainroy https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy

**Comment by kagurainroy** [comment]
@breakwa11 
1.已经按页面中的指导 将chrome快捷方式添加命令行，
![image](https://cloud.githubusercontent.com/assets/22196444/25743390/b50a1a4a-31c6-11e7-9ba1-0e2e88377eac.png)
但是没发现差别 还是连接不上 

2.然后按页面中的 
_**_**“或者您也可以在Chromium选项中完全禁止DNS预加载。请在选项的"Show advanced settings..."下方取消选择此选项：”**_**_
发现CHROME 58版本的设置里并没有该选项
![image](https://cloud.githubusercontent.com/assets/22196444/25743430/eba5e462-31c6-11e7-9708-6b6298ba4fde.png)

3.不过我在chrome://net-internals/#dns 里查询到 danmu.douyu.com这个服务器确实是被强制走IPV4直连了
![image](https://cloud.githubusercontent.com/assets/22196444/25743137/7e8eb288-31c5-11e7-9f84-2d58e28bf1fd.png)
然后我试着改本地以太网IPV4/V6的DNS服务器设置 统一改成谷歌DNS和我VPS的DNS 发现并不能解决此问题 DNS页面不变 
之后我试着修改HOSTS文件 将danmu.douyu.com解析为我VPS的地址和斗鱼客服人员提供的地址，发现页面里DNS确实改变了
![image](https://cloud.githubusercontent.com/assets/22196444/25743112/56e1f344-31c5-11e7-8455-99a51e342d7f.png)
但是依然解决不了此问题 仍然无法看弹幕

似乎没有更好的办法 可能只能向校园网投诉看看

**Comment by ysc3839** [comment]
好像在哪听说 Chrome 在没检测到 IPv6 网络时会优先走 IPv4。
