### ISSUE TITLE
升级SSR C# 4.2.3后，无法使用

### ISSUE THREAD

**Issue by heekei** [shadowsocksr/shadowsocksr-csharp#154]
![image](https://cloud.githubusercontent.com/assets/10609199/25734683/0c9c884e-3198-11e7-8294-e80b2b23d605.png)

**Comment by heekei** [comment]
然后恢复之前版本，就可以

**Comment by breakwa11** [comment]
@heekei 之前是啥

**Comment by heekei** [comment]
4.2.1
![image](https://cloud.githubusercontent.com/assets/10609199/25734737/a3ae0ef6-3198-11e7-856e-a85756e5e0b4.png)

**Comment by breakwa11** [comment]
@heekei 那协议设置的啥

**Comment by heekei** [comment]
{
	"configs" : [
		{
			"remarks" : "(电信联通移动直连)美国洛杉矶C3",
			"id" : "C38F304498954F89371F306E15887D76",
			"server" : "us-a.i-ss.site",
			"server_port" : 52362,
			"server_udp_port" : 0,
			"password" : "----------------------------",
			"method" : "aes-256-cfb",
			"protocol" : "auth_sha1_v2",
			"protocolparam" : "",
			"obfs" : "tls1.2_ticket_auth",
			"obfsparam" : "",
			"remarks_base64" : "------------------------------------",
			"group" : "server switch",
			"enable" : true,
			"udp_over_tcp" : false
		}
	],
	"index" : 0,
	"random" : false,
	"sysProxyMode" : 2,
	"shareOverLan" : false,
	"bypassWhiteList" : false,
	"localPort" : 1080,
	"localAuthPassword" : "XwBjHvuqJpjwzZ_8GSDM",
	"dns_server" : "",
	"reconnectTimes" : 2,
	"randomAlgorithm" : 0,
	"randomInGroup" : false,
	"TTL" : 0,
	"connect_timeout" : 5,
	"proxyRuleMode" : 0,
	"proxyEnable" : false,
	"pacDirectGoProxy" : false,
	"proxyType" : 0,
	"proxyHost" : null,
	"proxyPort" : 0,
	"proxyAuthUser" : null,
	"proxyAuthPass" : null,
	"proxyUserAgent" : null,
	"authUser" : null,
	"authPass" : null,
	"autoBan" : false,
	"sameHostForSameTarget" : false,
	"keepVisitTime" : 180,
	"isHideTips" : false,
	"token" : {

	},
	"portMap" : {}
}
![image](https://cloud.githubusercontent.com/assets/10609199/25734791/10c631ee-3199-11e7-9ea3-567a2e7d7701.png)

**Comment by breakwa11** [comment]
@heekei 那更新内容你看了没？

**Comment by heekei** [comment]
@breakwa11 auth_sha1_v2这个就是过时协议吗 : (

**Comment by breakwa11** [comment]
@heekei 是

**Comment by heekei** [comment]
@breakwa11 ......尴尬，谢谢你 👍
