### ISSUE TITLE
这个版本的客户端将鼠标光标移动到通知栏的小飞机上时不再显示服务器名称，请问是bug呢还是故意做出的修改更新呢~

### ISSUE THREAD

**Issue by xuanmpurdueedu** [shadowsocksr/shadowsocksr-csharp#157]
Please remove all above then write down your issue

My issue:
这个版本的客户端将鼠标光标移动到通知栏的小飞机上时不再显示服务器名称，请问是bug呢还是故意做出的修改更新呢~

**Comment by ysc3839** [comment]
> 确认你读完以上内容后，请删除以上所有内容，然后写下你的问题

**Comment by wxlg1117** [comment]
5.1.5的时候就这样啦,之前我也提出过这个问题

**Comment by xuanmpurdueedu** [comment]
@wxlg1117 应该是4.1.5吧

**Comment by breakwa11** [comment]
dup #135
