### ISSUE TITLE
WIN7系统代理设置无效，必须手动设置，为什么？

### ISSUE THREAD

**Issue by mrxhliu** [shadowsocksr/shadowsocksr-csharp#158]
我的电脑Win7，系统代理模式不管选哪个，IE代理设置都不生效，必须进Internet选项手动设置，尝试以管理员身份运行，退出所有安全软件也没用。
XP下没这个问题，用shadowsocks也没这个问题，独独ShadowsocksR有问题，这个怎么破？

**Comment by thisisjin** [comment]
@mrxhliu  我之前遇到过类似的问题貌似是因为IE8的缘故。升级到IE11就解决了。你是IE几？

**Comment by mrxhliu** [comment]
已经是IE11了

**Comment by mrxhliu** [comment]
@thisisjin

**Comment by thisisjin** [comment]
@mrxhliu 那我就不知道了。你等破蛙回复你吧

**Comment by breakwa11** [comment]
https://github.com/breakwa11/shadowsocks-rss/wiki/Windows-Internet-Options

**Comment by mrxhliu** [comment]
@breakwa11 按这个设置了，还是无效

**Comment by breakwa11** [comment]
IE里的属性->高级->启用增强保护模式，去掉钩，然后重启计算机，必须重启才生效

**Comment by breakwa11** [comment]
高级的HTTP设置里，通过代理连接使用HTTP 1.1 也要打钩

**Comment by breakwa11** [comment]
麻烦反馈最新情况

**Comment by mrxhliu** [comment]
@breakwa11 已经按你说的设置，去掉增强保护模式的勾，安全选项卡里去掉勾，我甚至把所有安全级别降到最低，然而问题依旧

**Comment by mrxhliu** [comment]
最近的三个版本我都试用，都不行，但原版SS却很好用，根本不用改什么设置 
对了，会不会跟我的.NET版本有关？我的是.NET 4.6.2

**Comment by breakwa11** [comment]
那你用的IE是64位还是32位

**Comment by mrxhliu** [comment]
64位的，刚尝试降级到.NET 4，还是没用

**Comment by breakwa11** [comment]
麻烦你截图刚才说的那些地方的配置，以及请确认保证修改后有重启机器，是重启机器不是重启IE

**Comment by mrxhliu** [comment]
@breakwa11 
![111](https://cloud.githubusercontent.com/assets/28480827/25839017/70e5a78a-34c8-11e7-8a29-9e4ab825207e.PNG)
![333](https://cloud.githubusercontent.com/assets/28480827/25839016/70e3ca28-34c8-11e7-883b-428000dcc50e.PNG)
![444](https://cloud.githubusercontent.com/assets/28480827/25839019/71232db2-34c8-11e7-9216-ca6c5e20ca1c.PNG)

我的问题是这个地方必须手动设置，在软件里切换无效
![666](https://cloud.githubusercontent.com/assets/28480827/25839018/71209d18-34c8-11e7-8cfe-b5a6040902ce.PNG)

**Comment by mrxhliu** [comment]
设置后都重启过电脑

**Comment by breakwa11** [comment]
截图一下SSR的exe属性页

**Comment by mrxhliu** [comment]
@breakwa11 

![2133123](https://cloud.githubusercontent.com/assets/28480827/25839258/8845eb50-34c9-11e7-835b-97ebe7c7ca41.PNG)

**Comment by mrxhliu** [comment]
![2 000233](https://cloud.githubusercontent.com/assets/28480827/25839335/cac7301a-34c9-11e7-9be2-bebe0ed9c0d4.PNG)

**Comment by breakwa11** [comment]
你先把自动配置脚本的地址清空，代理服务器的也清空，再用客户端设置一下，是能自动填上，但只是没打钩吗？

**Comment by mrxhliu** [comment]
@breakwa11 
代理设置是我手动设置或用原版SS设置的痕迹，不是SSR生成的。
我刚试了，这些记录清不掉，退出重进又有了，所以我手动改成别的了，然后用SSR设置，发现那些灰色的字无变化，依然是我手动设置的，也不会自动打勾。所以说，SSR在我电脑上对IE代理的设置完全无效。
已关闭所有安全软件

**Comment by breakwa11** [comment]
> 我刚试了，这些记录清不掉，退出重进又有了

这是什么意思？至少地址那个可以清掉吧？自动配置脚本那总可以在打钩状态随便写点内容吧
你别光用文字描述，你把你改成什么截图

**Comment by mrxhliu** [comment]
在“连接”选项卡下有一行字：某些设置由系统管理员进行管理，点设置打开微软的网站，但好像也没什么
https://support.microsoft.com/zh-cn/help/17441/windows-internet-explorer-change-reset-settings?ocid=IE10_group_policy

![666](https://cloud.githubusercontent.com/assets/28480827/25840127/1df9f558-34cd-11e7-98db-77399e85e11c.PNG)

**Comment by breakwa11** [comment]
那你能先按我说的来做一下么

**Comment by mrxhliu** [comment]
> 这是什么意思？至少地址那个可以清掉吧？自动配置脚本那总可以在打钩状态随便写点内容吧
你别光用文字描述，你把你改成什么截图

我把自动配置里的内容全删掉，然后去掉勾，保存退出，重新进，发现之前的自动配置脚本还在，但没打勾（灰色的），所以我另填了一个脚本地址：http://127.0.0.1/pac，保存退出，重进去掉勾，然后用SSR软件测试，一切都没变化，我知道SSR的自动配置地址后面是跟了很长一串字符的

**Comment by mrxhliu** [comment]
都是按你说的做的   一切的可能我都想到了 试过了  还是不行

**Comment by breakwa11** [comment]
那你用的SS是什么版本

**Comment by mrxhliu** [comment]
![ss](https://cloud.githubusercontent.com/assets/28480827/25840664/35ab9394-34cf-11e7-92f4-0114fb7088f9.PNG)

**Comment by mrxhliu** [comment]
SS是下载打开就能直接用，都没问题
SSR我都尝试右键以管理员身份运行，也不行

**Comment by breakwa11** [comment]
你有TG嘛？这样一来一回太累了

**Comment by mrxhliu** [comment]
汗，TG 是什么？

**Comment by cqhtyi** [comment]
TG -> Telegram

**Comment by mrxhliu** [comment]
加我
mrxhliu

**Comment by mrxhliu** [comment]
@breakwa11 
mrxhliu
