### ISSUE TITLE
关于SSR Win版的菜单建议

### ISSUE THREAD

**Issue by mrxhliu** [shadowsocksr/shadowsocksr-csharp#159]
菜单“系统代理模式”下有4个子菜单，感觉“不修改系统(IE)代理”没什么作用，保留“不经过代理直连”、“PAC模式”、“全局模式”这3个就可以了。另外“PAC”和“代理规则”这两菜单是不是重复了？

个人认为SS原版的菜单设置很合理

**Comment by ysc3839** [comment]
不修改是为了防止覆盖原有的代理设置，比如我手动设置了IE代理，一打开SS就被覆盖掉了，还得手动改一次很麻烦，选了这个就没问题了。

**Comment by mrxhliu** [comment]
@ysc3839 明白
那PAC和代理规则这两菜单是不是重复了？

**Comment by ysc3839** [comment]
PAC是浏览器处理的，代理规则是SSR处理的
