### ISSUE TITLE
让用户选择是否启动时自动更新、是否保护PAC

### ISSUE THREAD

**Issue by pk000** [shadowsocksr/shadowsocksr-csharp#161]
有时候不希望每次启动客户端都检查更新，特别是给家人设置好开机启动，不希望家人老是看到提示不知道怎么做。
或者想停留在某个固定版本一段时间，不希望每次启动都提示更新。
SS-win版客户端有选项可以选择是否启动时自动更新，希望SSR-win也有同样的选项。

另外，SSR的pac链接默认带有auth，可否和SS-win版那样提供是否保护PAC选项？
平时需要用pac的时候不需要复制冗长的链接，如果没有auth，那样只需要记住端口就可以使用pac了。
特别是在局域网内共享pac的情况下，很方便。
有安全性考虑的可以选择保护PAC，不担心局域网内安全的，完全可以不保护PAC。

**Comment by breakwa11** [comment]
下个版本的PAC仅针对本地地址强制AUTH
我认为现在的更新提示已经足够了，你不理它不就好了

**Comment by EMLVIRUS** [comment]
> 我认为现在的更新提示已经足够了，你不理它不就好了

某些强迫症 ~*態~ ：看着多出一个菜单选项很不爽

**Comment by pk000** [comment]
是的，对于强迫症来说，还是不希望每次启动发现新版本都出现提示的……
