### ISSUE TITLE
failed to recv data in HandshakeAuthReceiveCallback时自动重启客户端

### ISSUE THREAD

**Issue by nqzhang** [shadowsocksr/shadowsocksr-csharp#166]
![image](https://cloud.githubusercontent.com/assets/12559853/25893731/96f8d350-35ab-11e7-93e0-7bf340b7440a.png)
服务端除了能连接时的日志，这个错误后没有其他日志。
客户端版本4.2.1 
系统windows10专业版 1607 
在一段时间过后 好像链接被关闭了 然后就无法使用了 这时候换个节点或者重启下ssr就好了 这种情况下能否自动重启下 不然手动重启很麻烦

Please remove all above then write down your issue

**Comment by ysc3839** [comment]
> 确认你读完以上内容后，请删除以上所有内容，然后写下你的问题
