### ISSUE TITLE
Windows 7 在升级 .Net Framework 4.7 后 只监听 IPv6 的 1080 端口了

### ISSUE THREAD

**Issue by vibbow** [shadowsocksr/shadowsocksr-csharp#167]
SSR版本: 4.2.3 (.Net Framework 4.0 版)
Windows版本: Windows 7 x64

问题描述：
之前使用都是没问题的，手动安装了 .Net Framework 4.7，并更新了最新的补丁后 （这两者是同时进行的，不确定是单独因素还是组合因素造成的），SSR就只监听 IPv6 的1080端口了。

SSR启动日志：
[2017-05-10 18:59:29] [Error] connect to update server error
[2017-05-10 18:59:35] ShadowsocksR started on port 1080

**Comment by breakwa11** [comment]
那到底有没有影响你的使用呢？
