### ISSUE TITLE
为什么手机上开启分应用代理后无法正常访问谷歌商店了啊

### ISSUE THREAD

**Issue by shadowdreamer** [shadowsocksr/shadowsocksr-csharp#169]
不用分应用代理的时候正常，使用分应用代理后，谷歌商店出现“需要验证谷歌账户，登陆自己的账户什么的”
分应用代理使用的是绕行模式，绕行的有QQ、微信、一些视频软件等应用。

**Comment by ysc3839** [comment]
这是 [shadowsocksr-android](https://github.com/shadowsocksr/shadowsocksr-android) 的问题，你不应该在这里提交。
