### ISSUE TITLE
增加NTLM前置代理支持

### ISSUE THREAD

**Issue by pk000** [shadowsocksr/shadowsocksr-csharp#171]
有些公司内网需要经过NTLM/NTLMv2代理才能上外网。
目前SSR之支持普通HTTP代理或者Socks5代理，不能使用NTLM代理。
希望增加NTLM前置代理支持。

**Comment by breakwa11** [comment]
@pk000 短期内不考虑，建议本地开一个代理把NTLM转为普通的http代理再让SSR配置即可

**Comment by twfeiyu** [comment]
你可以使用 http://cntlm.sourceforge.net/  CNTLM作为中转

**Comment by twfeiyu** [comment]
SSR --> CNTLM (with NTLM / Kerberos 认证) --> 你的公司代理服务器

**Comment by pk000** [comment]
嗯，目前只能再运行一个cntlm了。
