### ISSUE TITLE
Google 验证

### ISSUE THREAD

**Issue by shermans** [shadowsocksr/shadowsocksr-csharp#172]
你好,

关于Google验证
可能大家很普遍的会遇到的问题.

我的设想是,可不可以增加一个功能,
合适的位置,应该是在  选项设置->服务器负载均衡   这里.
用户可以自定义,当我访问Google的时候,自动不使用某几个SS账号.或者自己指定使用某几个SS账号.

以此来避开Google验证.

感谢

**Comment by somelee** [comment]
你可以使用群组功能啊，兄弟

**Comment by BakaChinatsu** [comment]
使用 端口设置 配合 [Proxy SwitchyOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif) 即可。

**Comment by breakwa11** [comment]
如 @BakaChinatsu 所说，这样组合就能解决了

**Comment by shermans** [comment]
感谢解答

研究了一下,  @somelee 说的群组功能里面没看明白怎么能实现


@BakaChinatsu 说的端口设置.找了一下看到了

以下给和我差不多的小白看的.

任务栏右键点击SSR图标.->端口设置.
里面可以设置某个端口,只连接指定的SS服务器
然后在Proxy SwitchyOmega 定义Google连接该端口..

等于是给Google指定单独的规则.来避开Google验证.

**Comment by shermans** [comment]
配合 @somelee 说的群组功能,可以设置指定Google仅通过某个群组.
