### ISSUE TITLE
源码用VS2012编译不过去了，有很多地方用了新的语法，说明是不是得改了。

### ISSUE THREAD

**Issue by skyakira** [shadowsocksr/shadowsocksr-csharp#173]
我用VS2017调试通过了。估计后期是用vs2015开发的吧。

**Comment by breakwa11** [comment]
@skyakira 一直都是用2015

**Comment by skyakira** [comment]
ReadMe下面的Develop说明

Visual Studio Express 2012 is recommended.

**Comment by breakwa11** [comment]
@skyakira 4年没改，你说呢
