### ISSUE TITLE
为什么SSR的开机启动设置需要管理员权限？

### ISSUE THREAD

**Issue by Wows233** [shadowsocksr/shadowsocksr-csharp#174]
如题。SS就不需要。并且也可以直接添加快捷方式到启动文件夹的吧？一些其他方法也不需要权限啊。。偏偏要修改注册表？

**Comment by ysc3839** [comment]
我建议你手动在启动文件夹里面创建个快捷方式

**Comment by Wows233** [comment]
我目前就是这样的。只是来反馈一下

**Comment by breakwa11** [comment]
为了解决win10的坑

**Comment by Wows233** [comment]
win10有什么坑？

**Comment by breakwa11** [comment]
@Wows233 搜索旧issue

**Comment by Wows233** [comment]
我在启动里添加快捷方式是正常的

**Comment by stardock** [comment]
要不要管理员更改根本无所谓，反正都是来源软件
能用就行

**Comment by sumspec** [comment]
软件往系统目录写入文件是要管理员权限的
如果软件你的放到了C盘
那就给你的软件文件夹加上写入权限
