### ISSUE TITLE
4.3.1版本无法上网

### ISSUE THREAD

**Issue by CCMEOW** [shadowsocksr/shadowsocksr-csharp#176]
ss版本4.3.1
操作系统win10
pac模式下无法上网，提示http error code 503，直连可以浏览国内网站
服务器是4.0.5的config文件导入的，已确认没有填错

**Comment by CCMEOW** [comment]
补充日志

[2017-05-16 16:49:05] ShadowsocksR started on port 1080
[2017-05-16 16:49:17] [Error] connect to update server error
[2017-05-16 16:50:13] ShadowsocksR started on port 1080
[2017-05-16 16:50:27] [Error] connect to update server error
[2017-05-16 16:52:57] ShadowsocksR started on port 1080
[2017-05-16 16:53:09] [Error] connect to update server error
[2017-05-16 16:54:11] ShadowsocksR started on port 1080
[2017-05-16 16:54:25] [Error] connect to update server error
[2017-05-16 16:55:18] [Error] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 连接被意外关闭。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadPACCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-05-16 17:00:27] ShadowsocksR started on port 1080
[2017-05-16 17:00:39] [Error] connect to update server error
[2017-05-16 17:06:47] ShadowsocksR started on port 1080
[2017-05-16 17:06:59] [Error] connect to update server error
[2017-05-16 17:11:59] [Error] connect to update server error

**Comment by breakwa11** [comment]
@CCMEOW 那全局模式能不能上？那你服务器统计页的截图呢

**Comment by CCMEOW** [comment]
统计页是服务器连接统计那个吗？不知道为啥传不上图，看了下全都是0
全局模式也不能上

**Comment by CCMEOW** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentOutOfRangeException: InvalidArgument=“0”的值对于“SelectedIndex”无效。
参数名: SelectedIndex
   在 System.Windows.Forms.ListBox.set_SelectedIndex(Int32 value)
   在 Shadowsocks.View.ConfigForm.DeleteButton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.6.1648.0 built by: NETFXREL3STAGE
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ShadowsocksR
    程序集版本:4.3.1.0
    Win32 版本:4.3.1.0
    基本代码:file:///C:/software/ShadowsocksR-4.3.1-win/ShadowsocksR-dotnet4.0.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.6.1647.0 built by: NETFXREL3STAGE
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Drawing.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.resources/v4.0_4.0.0.0_zh-Hans_b03f5f7f11d50a3a/System.Drawing.resources.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.6.1647.0 built by: NETFXREL3STAGE
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

![image](https://cloud.githubusercontent.com/assets/12898486/26100953/00be70aa-3a62-11e7-9618-e565e30df63e.png)
当我试图删掉所有服务器手动添加一个试试的时候，删除最后一个给我报了这个错

**Comment by breakwa11** [comment]
那你就添加了再删，不可以全删

**Comment by takwai** [comment]
更新到 4.3.1 后，家里电脑和公司电脑都遇到此问题了。一律都是报 HTTP 503。

**Comment by breakwa11** [comment]
你们都有一个共同特点，最关键的config偏偏不说，协议加密混淆是什么偏偏不讲

**Comment by hhiew** [comment]
我这也是4.31和4.23都不能上网,同样的配置4.22可以
加密:rc-md5
协议:auth_sha1_v2
混淆:tls1.2_ticket_auth
混淆参数:intl.aliyun.com

**Comment by breakwa11** [comment]
所有人全部给我去看4.2.3的更新记录，还用auth\_sha1, auth\_sha1\_v2的别和我废话
