### ISSUE TITLE
升級之後不能使用，舊版正常

### ISSUE THREAD

**Issue by JimmyChangJY** [shadowsocksr/shadowsocksr-csharp#177]
我花了兩天還是解決不了這個奇怪的問題
4.1.5 一個檔案夾
4.2.3 一個檔案夾
4.3.1 一個檔案夾
同一個 gui-config.json 
使用 4.1.5 一切正常
YOUTUBE可以飆到 2K  都很順...

但是 4.2.3 與 4.3.1 就是不能用
不管是電腦重新開機，或是整個 reset Chrome or Firefox or IE 
我都試過了，Cache 也都清乾淨，就是不能用
log 出現[Error] connect to update server error
然後 Chrome 出現
www.google.com 未傳送任何資料。
ERR_EMPTY_RESPONSE
已經試了兩天，就是不能用新版本
現在還是用 4.1.5 一切正常
有人知道什麼問題嗎？

**Comment by qhfls** [comment]
4.2.3后彻底删除了过时协议，你看看是不是服务器不支持新协议

**Comment by JimmyChangJY** [comment]
不同的版本但是同一個 gui-config.json
表示不管甚麼版本，設定的協議都是同一個
auth_sha1
tls1.2_ticket_auth
我一律都設定這兩個

**Comment by breakwa11** [comment]
已废除
