### ISSUE TITLE
win10更新1703版本后系统代理模式PAC模式会断掉

### ISSUE THREAD

**Issue by a6372953** [shadowsocksr/shadowsocksr-csharp#178]
win10更新到1703创意者版本后SSR系统代理模式使用PAC模式时一般几十秒后就无法连接上。然后需要手动切换系统代理模式，再切换回PAC模式，才能连接，持续几十秒之后会再次断掉。尝试了SSR4.1.4-4.3.1之间的所有版本都会有这个问题。

**Comment by breakwa11** [comment]
@a6372953 这是win10的问题，和SSR没有任何关系

**Comment by a6372953** [comment]
@breakwa11 谢谢大佬回答，那么现在只能系统还原了，这个问题太折磨人了。
