### ISSUE TITLE
Shadowsocks 错误: 未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by n7then** [shadowsocksr/shadowsocksr-csharp#179]
---------------------------
Shadowsocks 错误: 未将对象引用设置到对象的实例。
---------------------------
System.NullReferenceException: 未将对象引用设置到对象的实例。

   在 Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)

   在 Shadowsocks.Controller.ShadowsocksController.Reload()
---------------------------
确定   
---------------------------

版本 4.3.1
原因 早上更新用了一段时间后,莫名打不开不是HTTPS的网站,后续以为是LSP问题,强修lsp然后重启在打开SSR就会出现以上报错,后续尝试回滚(4.1.5)依然有此错误,无力...

**Comment by breakwa11** [comment]
信息不足，我不知道你这到底是LOG还是弹出窗口，而且按你说明我没有办法复现

**Comment by n7then** [comment]
弹出窗口,出现在比如 启动SSR,开启服务器编辑界面点确定的时候.
环境是Win10 X64 LTSB .
目前回滚到4.1.5版本可以正常使用,跟4.3.1比如4.2.X尝试过一次是一样的情况.
再多的没法提供,技术有限,抱歉了.

**Comment by breakwa11** [comment]
@n7then 那试试新版本另建目录重新导入，不要使用之前的配置文件
