### ISSUE TITLE
ShadowSocks 与Net framework 兼容问题

### ISSUE THREAD

**Issue by itRookieMonster** [shadowsocksr/shadowsocksr-csharp#181]
shadowsocks配置成功以后 无法使用。咨询客服以后他们说可能是Net Framework问题  然后建议我issue 到这里想请大家帮忙看下 ：

配置环境：
 win 10.0.14393  shadowsocks 4.0.1 chrome 58.0.3029.110

shadowsocks.log:

[2017-05-20 21:30:16] Shadowsocks started
[2017-05-20 21:30:19] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

同样的方法在别的电脑上配置了能使用 在自己的电脑上就不行，试过ss2.0 4.0 都不行

**Comment by breakwa11** [comment]
和这项目没有任何关系
