### ISSUE TITLE
比较新的版本（如4.3.1和4.2.3）如果端口被占用，启动客户端时好像不提示了

### ISSUE THREAD

**Issue by BobKevinStuart** [shadowsocksr/shadowsocksr-csharp#182]
比较新的版本（如4.3.1和4.2.3）如果端口被占用shadowsocksr客户端启动时好像不提示了。前几天遇到无法使用的问题，确认服务器无异常后换用shadosocks版客户端提示端口被占用，Kill掉占用端口的进程后再使用shadosocksr恢复正常。

**Comment by breakwa11** [comment]
@BobKevinStuart 那么你能先确认一下么

**Comment by BobKevinStuart** [comment]
好吧，那我去掉“好像”两个字，上次已确认。当时用的是4.3.1版的shadowsocksr，浏览器提示“代理服务器拒绝连接”，下载4.2.3版再次尝试，依然，后来下载shadowsocks客户端，设置好服务器和本地端口，退出重新启动，提示端口被占用。终止占用端口的进程后，再次使用4.3.1版的shadowsocksr，正常。使用shadowsocksr客户端时并未提示端口被占用。

**Comment by breakwa11** [comment]
@BobKevinStuart 我意思是，用相同操作同现一下你的记忆中的结果

**Comment by BobKevinStuart** [comment]
因为占用shadowsocksr端口的程序的端口有一定的随机性，为方便重现错误，先查找到占用程序目前的端口为1174，然后将shadowsocksr本地端口设置为相同的1174端口，保存后关闭shadsocksr后重新打开，未报错，然后更新PAC文件，提示错误，打开shadowsocksr日志，显示如下：

[2017-05-22 21:23:33] [Error] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1174
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 System.Net.DownloadStringCompletedEventArgs.get_Result()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)



采用同样的方法，设置shadowsocks客户端本地端口为1174，保存时立即提示端口被占用，关闭后重新打开，提示端口被占用，日志如下：

[2017-05-22 21:35:43] System.Exception: 端口已被占用 ---> System.Net.Sockets.SocketException: 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   --- 内部异常堆栈跟踪的结尾 ---
[2017-05-22 21:35:47] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1174
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by breakwa11** [comment]
因为IPv6的端口监听成功了

**Comment by breakwa11** [comment]
更新
