### ISSUE TITLE
关于HTTP代理端口和关闭

### ISSUE THREAD

**Issue by leonardwu** [shadowsocksr/shadowsocksr-csharp#185]
C#客户端一直都有提供HTTP代理。但是端口号一直都在随机状态，根本不能手动设置，也不方便在需要的时候使用。而且还不能关闭这个功能。

**Comment by ysc3839** [comment]
HTTP 端口就是选项设置里面的端口。Privoxy 只是用来把 HTTP 协议转换成 SOCKS 协议。

**Comment by leonardwu** [comment]
抱歉 我重来没找到过 选项在哪里
