### ISSUE TITLE
utorrent和弹弹play两个磁力链接下载软件配置好ssr本地代理之后无法正常使用，通过sockscap64启动则可以

### ISSUE THREAD

**Issue by kagurainroy** [shadowsocksr/shadowsocksr-csharp#186]
最近在用弹弹play和utorrent下载 share.dmhy.org上提供的磁力链接时发现 
在shadowsocks4.3.1版本下 无法正常下载磁链

![default](https://cloud.githubusercontent.com/assets/22196444/26359452/1e061806-4008-11e7-898b-6b8707ef910d.png)
这是我在弹弹play客户端中的本地代理设置  经检验可以正常更新 也能在首页找到番剧表 也可以下载第三方弹幕库
但是在下载磁链文件时 会一直无法成功下载 速度始终为0KBS 无法连接上其他做种者
![1](https://cloud.githubusercontent.com/assets/22196444/26359682/b1c8a8f6-4008-11e7-831d-282339f1f1f0.png)

之后我试着用utorrent 2.2.1 2.0.4 在代理设置里如下配置 也没办法成功下载种子
![4](https://cloud.githubusercontent.com/assets/22196444/26359739/d4d1268e-4008-11e7-976e-09f54dee6e48.png)

但是如果在同样的ssr配置下 启用sockscap64 在sockscap64里设置 本地socks5代理 127.0.0.1:1080
之后从sockscap64里启动弹弹play 则能够正常下载磁链文件
![2](https://cloud.githubusercontent.com/assets/22196444/26359799/fbdd5cc0-4008-11e7-8cb0-c7ff2eb16e75.png)

我印象中我之前的用的版本是没有这个问题的 所以我又尝试了一遍4.1.5版本的ssr 但是发现也出现了此问题

**Comment by breakwa11** [comment]
LOG呢？服务器统计界面截图呢？你光说你那个不能用，一点用都没有

**Comment by kagurainroy** [comment]
@breakwa11 
![image](https://cloud.githubusercontent.com/assets/22196444/26363039/625a8988-4012-11e7-9526-9faa891c2f51.png)
清空log之后重启ssr 开始下载磁链文件10分钟之后的log和服务器统计界面如图


这是用sockscap64开启弹弹play之后的截图
![default](https://cloud.githubusercontent.com/assets/22196444/26363409/885e9736-4013-11e7-97ed-c54782f2a088.png)

[shadowsocks_2017-05.txt](https://github.com/shadowsocksr/shadowsocksr-csharp/files/1022805/shadowsocks_2017-05.txt)

这是从23:38:59 开始的LOG文件 从23:50:00左右开始是我用sockscap64启动弹弹play的

**Comment by breakwa11** [comment]
你单独测试utorrent的log给我看看

**Comment by kagurainroy** [comment]
![image](https://cloud.githubusercontent.com/assets/22196444/26365818/56734520-401b-11e7-815e-d5d9ccf55c7d.png)

这是utoorent的测试，ut中开始下载到截图时一共八分钟

**Comment by kagurainroy** [comment]
发现2.0.4版本的ut 在勾选resolve hostsnames though proxy和 use proxy server for p2p connections 之后可以正常使用ut

**Comment by breakwa11** [comment]
看起来你的BT软件就没有按配置去连接
