### ISSUE TITLE
代理规则选项有时候会不管用

### ISSUE THREAD

**Issue by LBYPatrick** [shadowsocksr/shadowsocksr-csharp#190]
### 版本
SSR 4.3.1.0

### 系统
Windows 10 1703 创意者更新

### 地区
广东，SS架在日本Linode

### 测试用网络
中国移动**4G/宽带**，中国联通4G，中国电信宽带

### 啥情况
在代理规则里选择绕过中国大陆和局域网，登录淘宝和ip.cn时依然显示是海外用户（那就说明还是走了SS），速度上也明显慢了，ip138依然显示的是SS的IP （已确认是SSR的问题，因为不是浏览器缓存的问题）

**Comment by breakwa11** [comment]
@LBYPatrick 这是dns导致的，不是规则问题

**Comment by LBYPatrick** [comment]
好的，我再去试试。
