### ISSUE TITLE
V4.3.1版本更新后 原有服务器无法访问 已手动更新但无效

### ISSUE THREAD

**Issue by robetchensong** [shadowsocksr/shadowsocksr-csharp#197]
作者你好！一直在用你的软件，非常感谢！

反馈一个问题，V4.3.1版本更新后（包括V4.4.2），发现之前保存的服务器全都无法访问了。服务器节点都是付费购买的。
具体的情况是链接服务器后，出现无法访问网页（页面无法打开）的现象。

但使用V4.2.3或之前的版本，毫无问题，请查证。如有疑问，请联络755766198@qq.com 

非常感谢！

**Comment by breakwa11** [comment]
@robetchensong 到底什么配置

**Comment by robetchensong** [comment]
已回复邮件，请查收，如果没有收到，请告知，谢谢！

**Comment by robetchensong** [comment]
请问收到了吗？有没有测试，是否是我说的那种情况？谢谢！

**Comment by breakwa11** [comment]
竟然敢用QQ邮箱发，一年都不可能收到
