### ISSUE TITLE
订阅自动更新后所选服务器自动重置了..

### ISSUE THREAD

**Issue by wxlost** [shadowsocksr/shadowsocksr-csharp#198]
我有3个节点.默认用第二个或者第三个.开了订阅后.自动更新成功.服务器自动选择了1.而不是保持之前的不变.....这样用户每次自动更新都要选择一次.不是增加负担么...
希望能增加一个功能就是根据网站设置自动读取设置好的默认节点(根据导入顺序的序号或者节点ID).
例如网站设置
LV3默认节点=7
LV2默认节点=5
LV1默认节点=3

判断用户节点存在7.存在选择他.不存在继续向下判断节点5

**Comment by breakwa11** [comment]
你看看新版本如何
