### ISSUE TITLE
更新V4.4.4版本后还是无法链接服务器

### ISSUE THREAD

**Issue by robetchensong** [shadowsocksr/shadowsocksr-csharp#202]
和之前的问题一样，使用V4.2.3能够正常访问，同样的设置在V4.4.4版本还是无法连接服务器。请查证，谢谢！软件编译的很好，不希望因无法使用而放弃这个软件。

另外我不是专业人士，所以没有办法专业的进行提问，希望不要有意见，谢谢！

**Comment by robetchensong** [comment]
不太清楚V4.3以后的版本用了什么机制，导致协议不一样了？还是怎么，旧版能够顺利连接的，新版本死活就是没反映。服务器列表也更新过（手动），账户是付费的，不会有问题。希望能够得到重视

**Comment by wenliyang** [comment]
不需要你进行专业的提问，但象这种，截个图还是需要的吧，你的服务器信息，看看你的加密、协议和混淆都是用的什么，其它敏感信息可以自行涂掉

**Comment by robetchensong** [comment]
我都发邮件了啊，以为能收到呢

**Comment by robetchensong** [comment]
![-1](https://cloud.githubusercontent.com/assets/25184691/26783534/4f653cd8-4a2b-11e7-9260-2e6ce0ee3c86.png)
![-2](https://cloud.githubusercontent.com/assets/25184691/26783533/4f6157ee-4a2b-11e7-9957-1711bbdded47.png)

上图能否打开？是我的付费服务器信息，可以随时测试
吾皇VPN使用PAC / 个人链接那个使用全局模式

![-1](https://cloud.githubusercontent.com/assets/25184691/26783605/aa48636e-4a2b-11e7-9e6c-d4311ff2945f.PNG)
![-2](https://cloud.githubusercontent.com/assets/25184691/26783606/aa4cc152-4a2b-11e7-8d96-603f6289c442.PNG)

**Comment by robetchensong** [comment]
昨天作者第一时间问了我，我回了邮件，以为能够收到呢，真是不好意思。信息都在这里面，其他设置都是默认的，没有动，麻烦查验，谢谢！

**Comment by ccwy** [comment]
这能看出什么？发日志截图啊

**Comment by wenliyang** [comment]
试了你的第一张图提供的服务器，可以连接，4.4.4版本

我用的是浏览器加扩展，没用PAC方式

**Comment by ccwy** [comment]
另外你用不了不应该找你的SS商家？

SSR客户端我这里用着没什么问题

**Comment by robetchensong** [comment]
好吧，我再试试，难道和浏览器有关系？我用的是遨游

**Comment by qianchengqun** [comment]
`过来参观！！！`

**Comment by robetchensong** [comment]
无法链接的日志，请支招，谢谢



![default](https://cloud.githubusercontent.com/assets/25184691/26784205/ed613416-4a2e-11e7-9f06-8f01103d729a.png)

**Comment by robetchensong** [comment]
这个是V4.2.3可以顺利链接的日志 在这里交流就是学习，你们懂得比我多

![qq 20170605205006](https://cloud.githubusercontent.com/assets/25184691/26784523/a418b5d4-4a30-11e7-9021-43473c7c98f2.png)

**Comment by breakwa11** [comment]
exe文件属性是不是有锁定

**Comment by robetchensong** [comment]
没有啊，好烦人哦，好端端的软件为什么新版本无法使用，配置都是一样的
![1](https://cloud.githubusercontent.com/assets/25184691/26785317/4f6f6d94-4a34-11e7-9c29-1babb542853e.png)
![2](https://cloud.githubusercontent.com/assets/25184691/26785318/4f7735f6-4a34-11e7-99b4-d463e8d9bb5d.png)
![3](https://cloud.githubusercontent.com/assets/25184691/26785319/4faed452-4a34-11e7-916e-87a9075f5b9b.png)
![4](https://cloud.githubusercontent.com/assets/25184691/26785320/4fbbb762-4a34-11e7-8f0a-28cf7132d7ce.png)
![5](https://cloud.githubusercontent.com/assets/25184691/26785321/4fc2a018-4a34-11e7-84e5-6392246b0240.png)
![6](https://cloud.githubusercontent.com/assets/25184691/26785322/4fd6fb94-4a34-11e7-956d-0e719be0c162.png)

**Comment by robetchensong** [comment]
新版本怎么样都没戏，4.2.3什么问题也没有
![a](https://cloud.githubusercontent.com/assets/25184691/26785405/c0670ba6-4a34-11e7-9d33-f8f3c0cd3f35.png)
![qq 20170605211918](https://cloud.githubusercontent.com/assets/25184691/26785406/c06b3442-4a34-11e7-807a-35b8a489c63c.png)

**Comment by breakwa11** [comment]
到现在还是不知道你到底遇到什么异常

**Comment by MoozLee** [comment]
一样的问题，4.2.3可以用，以后的版本除了订阅的ssr可以用，其他的节点都不能连接。。。

**Comment by robetchensong** [comment]
看吧，有问题的不止我一个，估计是Windows 10版本和程序不兼容，望查正，谢谢

**Comment by daoxunchen** [comment]
我拿你的账号试了一下   4.5.0  可以用啊
windows10-1703

**Comment by Justsoos** [comment]
很有可能是本地端口问题，改掉本地端口试试。
或者是著名的那个问题～垃圾迅雷占用了系统1080端口，其他同端口程序都会出错。

**Comment by breakwa11** [comment]
超过1个月没有更新反馈，关了
