### ISSUE TITLE
PAC‘直连’使用二级代理

### ISSUE THREAD

**Issue by QC858020** [shadowsocksr/shadowsocksr-csharp#207]
代理服务器系统为Ubuntu16.04，服务器端使用dante建立Socks5代理，pam方式认证。客户端为SSR C# 4.4.5。代理端口已设定用户名和密码。
在选项设置中勾选“开启代理”以及“PAC‘直连’使用二级代理”，使用PAC模式时，对于判定为需要代理的网页可以经由代理服务器和ss服务器正常访问，但是如果判定为直连的网页，代理服务器拒绝连接。dante的日志里显示对于PAC判定为直连的连接请求不带认证信息。而那些要被转发至ss服务器的请求则包含正确的认证信息，是我哪里设置有问题吗？感觉去往代理的连接请求应该都包含认证信息啊。

**Comment by breakwa11** [comment]
PAM是什么认证？

**Comment by QC858020** [comment]
如果一定让我说清楚原理，大概对我来说有点难度。按照Dante的官网描述
https://www.inet.no/dante/doc/latest/config/auth_pam.html
PAM即Linux中的“可插拔式认证模块”。对于Dante而言，将method参数设置为"pam"时，就会对传入的连接使用PAM进行认证。
看这张图:
![default](https://user-images.githubusercontent.com/22014678/26983977-d6ac3204-4d3d-11e7-8d32-05befcb42b8a.JPG)
上面那行是PAC判定为“直连”的时候建立的连接，IP前面并没有带认证信息。而下面那行则是PAC判定为“使用代理”时连接到远程ss服务器所产生的连接，是带有pam@***的，所以我觉得大概是直连的连接没有携带认证信息导致了它的异常。但是由于没有抓包，也不是很确定。
我也试验了认证方式改为“username”，即使用系统的用户&密码文件，也会发生同样的问题，直连流量被拒绝连接，转发流量ok。
现在我也不确定是Linux上Dante的问题还是ssr的问题。。。如果作者您有空测试，我可以把服务器的控制权给您。谢谢。

**Comment by breakwa11** [comment]
那你就不要使用PAC的分流，改用代理规则做分流，因为PAC本来就不支持设置验证密码
