### ISSUE TITLE
试用 SSR 4.4.5 的一些担忧和问题反馈

### ISSUE THREAD

**Issue by WolfSkylake** [shadowsocksr/shadowsocksr-csharp#208]
不啰嗦，直接阐述主题：

1、在新版SSR中加入的“订阅”功能想法很好，但是我不建议默认情况下集成一个更新链接。这个世界上什么奇怪的人都有，如果随软件集成服务器订阅，会更快的透支软件生命周期，而且增大了被“有关部门”发现和查处的可能性。

改进思路：将服务器订阅链接从内置集成，改为下载页面公示，或放在WIKI。

2、在Windows10 1703 x64（15063.332）中，运行“ShadowsocksR-dotnet4.0.exe”，在服务器列表删除所有服务器后，会出现报错界面，提示信息 如下：

+——+——+——+——+——+——+——+——+——+——+——+——+——+——+——+

编辑服务器（local：1080）Version4.4.5
应用程序中发生了未经处理的异常。如果单击“继续”，
应用程序将忽略此错误并尝试继续。如果单击“退出”，
应用程序将立即关闭。
InvalidArgument =“0”的值对于“SelectedIndex”无效。
参数名：SelectedIndex

详细信息：
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentOutOfRangeException: InvalidArgument=“0”的值对于“SelectedIndex”无效。
参数名: SelectedIndex
   在 System.Windows.Forms.ListBox.set_SelectedIndex(Int32 value)
   在 Shadowsocks.View.ConfigForm.DeleteButton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.2098.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ShadowsocksR
    程序集版本:4.4.5.0
    Win32 版本:4.4.5.0
    基本代码:file:///E:/%E8%BD%AF%E4%BB%B6/ShadowSocks/TEST/ShadowsocksR-4.4.5-win/ShadowsocksR-dotnet4.0.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.2094.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.2093.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Drawing.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.resources/v4.0_4.0.0.0_zh-Hans_b03f5f7f11d50a3a/System.Drawing.resources.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.2098.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

+——+——+——+——+——+——+——+——+——+——+——+——+——+——+——+

**Comment by ysc3839** [comment]
自带的订阅服务器列表是放在 GitHub 上的，有关部门没办法。服务器则是热心人士提供的，他们提供时肯定有考虑这方面的问题。所以这并没有什么问题。

**Comment by WolfSkylake** [comment]
@ysc3839 
我指的是软件的 “软件设置”——“SSR服务器订阅设置” 中，随发行版软件集成了更新链接，这样的做法明显会留下把柄，个人感觉考虑欠妥当。我的建议是，在发行版软件中，不要集成更新链接。

如果测试版这样做，我觉得没什么问题。

**Comment by ysc3839** [comment]
@WolfSkylake 你没有理解我的意思，我说的就是你所说的更新链接。另外为什么会“留下把柄”？

**Comment by WolfSkylake** [comment]
@ysc3839 
我害怕被一些“小学生”举报使用这个客户端，不需要做任何设置就能科学上网，最后弄得跟SS原作者一样被请去“喝茶”。所以我认为不在客户端内添加“SSR服务器订阅设置”中的“更新链接”比较稳妥。

**Comment by ysc3839** [comment]
@WolfSkylake 不需要举报，TG肯定想清除这类软件，即使没有这个功能。至于会不会被请去“喝茶”，要看开发者的身份隐藏的好不好。跟有没有这功能一点关系都没有。

**Comment by WolfSkylake** [comment]
@ysc3839 
或许是我想多了吧，但我还是真心希望这个项目能长久做下去，原因都懂的。另外，我希望能尽快修复我上面提到的一个程序BUG，希望程序能越来越完美。

**Comment by breakwa11** [comment]
更新
