### ISSUE TITLE
删除服务器之后报错

### ISSUE THREAD

**Issue by wellkens** [shadowsocksr/shadowsocksr-csharp#210]
系统是win7x64，.net4.6.2，操作过程如下：
1、解压缩，目录不含中文
2、运行SSR，关闭服务器订阅的自动更新，代理模式变成直连
3、删除已经订阅的所有服务器
删除最后一个之后，程序报错，如图所示：

![qq 20170609101651](https://user-images.githubusercontent.com/22547715/26960716-e63c6c34-4d0b-11e7-847f-63b2a9227920.png)

此时点击继续程序不会被强制关闭，能不能使用没尝试，点击退出之后，程序被强制关闭，鼠标指向任务栏图标时图标消失，但进程中仍然存在，此时删除时会提示mgwz.dll在Privoxy打开而无法删除（如下图），而不是SSR客户端程序被占用

![qq 20170609102632](https://user-images.githubusercontent.com/22547715/26960717-e63dc674-4d0b-11e7-8d78-3baefa57b67e.png)

已经尝试过4.4.5、4.4.4、4.3.1、4.2.3、4.1.0：4.4.5、4.4.4和4.3.1均有此问题，4.4.5尝试了dotnet4.0和dotnet2.0，其它两个只运行了dotnet4.0，4.2.3和4.1.0均无此问题

**Comment by breakwa11** [comment]
发之前请先看是不是已经有新版本
