### ISSUE TITLE
功能越来越多，大部分都是用不到的，能否出个精简版本？只保留基本的扫码和连接服务器的功能

### ISSUE THREAD

**Issue by effzmt** [shadowsocksr/shadowsocksr-csharp#212]
现在新加的很多诸如负载均衡、流量统计、订阅等功能，普通只翻墙的用户根本用不上，还因为新功能的bug要频繁更新。
所以能否出个精简稳定版本？只保留基本的扫码和连接服务器的功能，半年左右或更长时间更新一次？

**Comment by breakwa11** [comment]
@effzmt 不可以

**Comment by koovier** [comment]
功能再多，也就几十兆。。怕啥。。

**Comment by effzmt** [comment]
@koovier 几十兆还不大啊？就为了一个简单的翻墙功能。况且为了这些新功能，还要频繁更新程序，麻烦。一般软件都有稳定版的，就这没有

**Comment by EMLVIRUS** [comment]
所以 为何你不用隔壁的ss呢

**Comment by daoxunchen** [comment]
源代码都在这儿，自己下回去编译呗
我之前服务商一直用v2那个协议（ssr删掉了），我都是自己下了代码又添回去再编译的

**Comment by y888** [comment]
看见新版功能变多也用不上 就懒得更新

**Comment by effzmt** [comment]
@EMLVIRUS 隔壁的更大更不好用！法克

**Comment by EMLVIRUS** [comment]
所以 你们真的在意那不到 5M 的硬盘空间跟这一点系统资源？

**Comment by daoxunchen** [comment]
@EMLVIRUS 那可是将近一个G啊

**Comment by EMLVIRUS** [comment]
> 将近一个 G 啊

![image](https://user-images.githubusercontent.com/16912240/27182395-8fd2a32a-520d-11e7-864d-e527a8828e9e.png)

Excuse me????? 我还自己加了料

**Comment by daoxunchen** [comment]
。。。老梗了
https://www.zhihu.com/question/26864682
@EMLVIRUS

**Comment by effzmt** [comment]
@EMLVIRUS 关键是没几天就要更新，好烦哪

**Comment by breakwa11** [comment]
现在逼你更新了？？
