### ISSUE TITLE
建议“代理规则”选项更名为“全局模式代理规则”

### ISSUE THREAD

**Issue by jorismq** [shadowsocksr/shadowsocksr-csharp#214]
因为，作为小白，不懂三个选项“系统代理模式”、“PAC”、“代理规则”究竟是什么样的关系。
从布局上来看是并列
可实际是应该是
“系统代理模式”
——————“PAC”
——————“代理规则”
特别是“系统代理模式”还有个“PAC模式”和“全局模式”的两个子选项。。。。完全懵圈。。。
我的理解是
“系统代理模式”
——————“PAC模式”——“PAC”
——————“全局模式”——“代理规则”
谢谢！
我是小白。

**Comment by ysc3839** [comment]
代理规则不管是否使用PAC都会生效的，PAC是浏览器处理，代理规则是SSR处理
