### ISSUE TITLE
代理规则选择绕过局域网和大陆时无法使用google.com

### ISSUE THREAD

**Issue by dcll222** [shadowsocksr/shadowsocksr-csharp#215]
绕过局域网, 绕过局域网和非大陆, 全局, 都正常.

只有选择绕过局域网和大陆时, 无法使用google.com, chrome提示ERR_CONNECTION_CLOSED, Firefox提示载入页面时与 www.google.com 的连接被中断。您尝试查看的页面无法显示，因为已收到数据的可靠性无法证实。

其他被墙网站大部分都正常, 少量无法解析dns

问题出现时SSR日志中不出现google.com相关条目, 看起来像是没有发送连接请求

**Comment by ysc3839** [comment]
我觉得是远程服务器断开的连接导致的

**Comment by breakwa11** [comment]
你的DNS被污染，而且你的代理规则应该不是全局

**Comment by didila** [comment]
這個問題我也可以補充我遇到的
連線模式為全局
代理規則設置為繞過局域網和大陸
只要DNS被汙染為127.0.0.1的網站幾乎無法使用
FACEBOOK最嚴重

另外。如果代理模式設置為PAC模式
代理規則設置為全局
服務器設置UDP OVER TCP
最常出現的狀況就是
DNS很大的機率出現只利用本地解析而不是遠程DNS解析
本地解析的結果得到的是污染IP，結果就是封鎖網站就上不去了

**Comment by breakwa11** [comment]
更新

**Comment by didila** [comment]
测试两天发现
系統代理模式為全局
代理規則設置為繞過局域網和大陸
127.0.0.1的问题还是没解决

而系統代理模式設置為PAC模式
代理規則設置為全局
连线状况似乎有比较好

**Comment by breakwa11** [comment]
那你更新了没有？？？

**Comment by didila** [comment]
有更新4.5.0

**Comment by breakwa11** [comment]
楼主的问题肯定解决了，你的问题和楼主不一样，你用的应该是firefox

**Comment by dcll222** [comment]
我换回了SS

2017-06-15 23:42 GMT+08:00 破娃酱 <notifications@github.com>:

**Comment by breakwa11** [comment]
下次如果你打算换软件，不想帮忙解决问题那早点说，或者干脆换了别发issue
