### ISSUE TITLE
建议改进订阅功能，增加多点订阅

### ISSUE THREAD

**Issue by shido520** [shadowsocksr/shadowsocksr-csharp#222]
如题，增加多点订阅，并能独立控制每一个订阅是否自动升级！

感谢作者提供这么好用的SS客户端！

**Comment by dddog999** [comment]
手机端好像有多个订阅源的？

**Comment by billng** [comment]
已经提过了，希望作者可以增加多条订阅地址功能，Android版已经实现了。
