### ISSUE TITLE
“自动禁用出错服务器”的功能 灰掉，无法勾选

### ISSUE THREAD

**Issue by ysj19921026** [shadowsocksr/shadowsocksr-csharp#223]
SSR版本是最新的4.4.6，“自动禁用出错服务器”的功能 灰掉，无法勾选，无论是否勾选其他的选项（负载均衡等相关选项），
如图

![ssr issue1](https://user-images.githubusercontent.com/19644162/27067112-a2471aaa-503b-11e7-8524-6efafed05a5f.jpg)

**Comment by breakwa11** [comment]
@ysj19921026 这是为了告诉你这功能删掉了，谢谢，别重复提问
