### ISSUE TITLE
windows xp 使用订阅更新节点信息时 配置文件发生错误

### ISSUE THREAD

**Issue by mengyyy** [shadowsocksr/shadowsocksr-csharp#224]
更新订阅 显示成功 但是配置文件节点导入不完整 部分节点信息丢失  如本地端口号 代理方式 等部分配置恢复成默认值

系统为 windows xp sp2
.net 4.0  2.0 均存在这个问题
ssr 版本为 4.4.6

_.net4.0_

[2017-06-13 16:02:25] System.IO.IOException: 文件“F:\lili\ssr\ShadowsocksR-4.4.6-win (2)\gui-config.json”正由另一进程使用，因此该进程无法访问该文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding)
   在 System.IO.File.ReadAllText(String path, Encoding encoding)
   在 Shadowsocks.Model.Configuration.LoadFile(String filename)

_.net2.0_

[2017-06-13 16:01:51] System.IO.IOException: 文件“F:\lili\ssr\ShadowsocksR-4.4.6-win (2)\gui-config.json”正由另一进程使用，因此该进程无法访问该文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding)
   在 System.IO.File.ReadAllText(String path, Encoding encoding)
   在 Shadowsocks.Model.Configuration.LoadFile(String filename)

**Comment by breakwa11** [comment]
正由另一进程使用，因此该进程无法访问该文件

错误不是已经中文写了吗

**Comment by mengyyy** [comment]
明白……看来我系统问题
