### ISSUE TITLE
建议让必应 (Bing) 过代理

### ISSUE THREAD

**Issue by zzq1015** [shadowsocksr/shadowsocksr-csharp#227]
在代理规则选择“绕过局域网和大陆”时，bing 为中国版。
建议过代理，使用国际版，限制更少
而且，本人已经把 `host.txt` 中 `.bing.com` 设为 `remoteproxy`，但是貌似没用

**Comment by breakwa11** [comment]
@zzq1015 修改后重新打开一下客户端，或随便修改任何一个设置保存才生效

**Comment by zzq1015** [comment]
@breakwa11 客户端已重启多次，bing 依然是中国版

**Comment by breakwa11** [comment]
你不修改你浏览器语言没用的

**Comment by Wows233** [comment]
bing直接走代理已经能搜索到敏感内容，不修改浏览器设置，域名还是cn.bing.com，但是结果变了

**Comment by zzq1015** [comment]
@breakwa11 跟 IP 有关，bing上搜“IP” 得到的是我的真实IP
全局代理无此问题

**Comment by Wows233** [comment]
那就是设置有误了，如果是chrome可以使用
Proxy SwitchyOmega切换代理，不用修改SS文件
https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif
fx也有相关的插件

**Comment by zzq1015** [comment]
升了4.5.1，日志：
[2017-06-16 01:49:22] [Info] Direct connect www.bing.com:443
[2017-06-16 01:49:22] [Info] Direct connect www.bing.com:443
[2017-06-16 01:49:22] [Info] Direct connect www.bing.com:443
[2017-06-16 01:49:22] [Info] Direct connect www.bing.com:443
[2017-06-16 01:49:22] [Info] Connect az29176.vo.msecnd.net:443
[2017-06-16 01:49:22] [Info] Direct connect login.live.com:443
[2017-06-16 01:49:24] [Info] Direct connect s3.cn.bing.net:80
[2017-06-16 01:49:24] [Info] Direct connect s1.cn.bing.net:80
[2017-06-16 01:49:24] [Info] Direct connect s3.cn.bing.net:80

Bing 不应该直连的

**Comment by breakwa11** [comment]
@zzq1015 那你编辑一下host.txt啊，默认里面有一条.bing.com localproxy，你应该把这条删掉

**Comment by zzq1015** [comment]
我把这条移到上面 remoteproxy 部分，并改为 remoteproxy

**Comment by breakwa11** [comment]
@zzq1015 我测试过完全没有问题，只要修改好，就是通过代理连接的

**Comment by zzq1015** [comment]
DNS 解析没有过代理吧
墙外解析 www.bing.com 得 13.107.21.200, 204.79.197.200
墙内解析 www.bing.com 得 202.89.233.103, 202.89.233.104
chn_ip.txt 删掉一行 202.89.232.0 202.89.239.255，www.bing.com 过代理了

**Comment by zzq1015** [comment]
要不把解析到的 IP 也输出？

**Comment by breakwa11** [comment]
@zzq1015 那你的host.txt肯定是没改对

**Comment by zzq1015** [comment]
host.txt .bing.com 改成 reject，重启SSR，bing 连接失败，其他网站正常
改回 remoteproxy，chn_ip.txt 没有 202.89.232.0 202.89.239.255，过代理
加回 202.89.232.0 202.89.239.255，又直连了

**Comment by breakwa11** [comment]
OK，这是个BUG，我改好了，你再从4.5.1那重新下载一个试试

**Comment by zzq1015** [comment]
@breakwa11 谢谢，现在终于过代理了
记得更新下载页的哈希值
issue 可以关了
