### ISSUE TITLE
关于全局代理中host文件问题

### ISSUE THREAD

**Issue by nehcnoel** [shadowsocksr/shadowsocksr-csharp#229]
你好，破娃酱
4.5.0（或4.5.1）目前发现启用绕过局域网和大陆选项（系统代理模式：全局），无法打开wikipedia，是不是host文件引起的？
已知在4.4.6版本中，同样的配置可以打开wikipedia。
具体环境如下
win 7 pro(64bit)   Chrome:59.0.3071.104  ssr:4.5.0

说下我个人的看法，本身全局代理中就是利用DNS自动识别IP地址来决定是否启用代理，增加host后反而不方便，需要开发者不定时更新host文件，这跟pac模式已经没有区别，所以我建议还是取消host功能。

**Comment by nehcnoel** [comment]
补充：
中文版wiki打不开，英文以及日文版可以打开。

**Comment by EMLVIRUS** [comment]
然而 也只有中文版的 Wikipedia 的域名被污染

**Comment by breakwa11** [comment]
那你给个理由为什么不取消pac功能而取消hosts

**Comment by nehcnoel** [comment]
@breakwa11 只是个人见解而已，因为毕竟也要考虑到用户使用习惯等因素。请问对于此issue是否有相关解决方案？
期待答复，谢谢。

**Comment by breakwa11** [comment]
@nehcnoel 解决办法是用4.5.1然后修改host文件删除一行.wikipedia.org localproxy

**Comment by nehcnoel** [comment]
@breakwa11 多谢。
