### ISSUE TITLE
使用pac模式，访问微信公众平台页面提示浏览器版本过低！

### ISSUE THREAD

**Issue by hejiadong0608** [shadowsocksr/shadowsocksr-csharp#231]
您好，我使用的配置是GFWList+Pac模式，其他设置都没有调整，就是添加了自己的服务器。使用ie11，windows10 64bit，访问微信公众平台网站提示
你正在使用的浏览器内核版本过低，微软已经不再提供技术支持，为避免可能存在的安全隐患，请尽快升级你的浏览器或者安装更安全的浏览器访问微信公众平台。
请问此问题是什么原因导致的，我应该如何解决？谢谢！

**Comment by hejiadong0608** [comment]
补充：用的系统为1703版。

**Comment by ysc3839** [comment]
请你试试不用代理访问有没有这个问题。

**Comment by hejiadong0608** [comment]
选择直接连接或者全局代理都是没有这个问题的，只有在pac模式下才会有这个提示。
@@ysc3839

**Comment by breakwa11** [comment]
@hejiadong0608 你应该是浏览器设置了局域网用兼容模式，而代理的时候就以为是局域网

**Comment by hejiadong0608** [comment]
我没有对ie11做任何跟兼容性有关的设置啊！
@breakwa11

**Comment by breakwa11** [comment]
@hejiadong0608 你不做不等于默认没有

**Comment by hejiadong0608** [comment]
@breakwa11
那应该怎样取消这个默认设置呢？

**Comment by hejiadong0608** [comment]
是这个选项吗？
在兼容性视图中显示 Intranet 站点
@breakwa11

**Comment by bxb100** [comment]
@hejiadong0608 设置 - 兼容性视图设置 - 将 在兼容性视图中显示..... 取消选择

**Comment by hejiadong0608** [comment]
@bxb100
好的，已经搞定了，谢谢！
