### ISSUE TITLE
中文维基百科无法访问，其他正常。

### ISSUE THREAD

**Issue by operatta** [shadowsocksr/shadowsocksr-csharp#232]
Windows C# 4.5.0版，系统代理PAC模式，无论更新PAC为“绕过大陆常见域名列表”、“绕过大陆IP”、“GFWList”哪种，都不能访问中文维基百科（zh.wikipedia.org），访问其他语言版本维基百科正常，如en.wikipedia.org，访问Facebook等网站也正常。不知什么原因？

**Comment by breakwa11** [comment]
dup #229
