### ISSUE TITLE
绕过局域网和大陆规则下中文维基百科网页不能自动代理的问题

### ISSUE THREAD

**Issue by lolipop132** [shadowsocksr/shadowsocksr-csharp#234]
升级到SSR 4.5.0版本后发现的这个问题。系统代理模式为全局，更新PAC为GFWList，代理规则为绕过局域网和大陆。在Chrome和Firefox最新版本浏览器的隐身浏览模式下均不能打开中文维基百科网页，需要临时调整规则为仅绕过局域网才能打开。
感觉很奇怪，因为中文维基百科被强了这么久了，为什么会一更新就在代理规则外了呢？好几个不同的词条和中文维基首页都试过了。

**Comment by breakwa11** [comment]
因为新的host.txt文件有错误
