### ISSUE TITLE
三星国行S8根据网站严格操作 无法使用

### ISSUE THREAD

**Issue by zhenbin-zhang** [shadowsocksr/shadowsocksr-csharp#235]
尊敬的工作人员（大大）好：手机按照网站的安卓流程操作，无法上网，提示连接成功，可是流量却无互联网连接！希望大大能帮忙解决一下，版本信息、配置、以及后续出现的情况如下列的图，最开始我以为是没有通过手机默认浏览器添加节点的缘故，可是后来还是不行，希望能帮忙解决问题，真心谢谢！

![default](https://user-images.githubusercontent.com/29544555/27287408-1ca4ac3c-5536-11e7-9d9f-6e48cf66ae2e.jpg)
![default](https://user-images.githubusercontent.com/29544555/27287411-2241c5e4-5536-11e7-9032-f57627739085.jpg)
![default](https://user-images.githubusercontent.com/29544555/27287419-27b591ea-5536-11e7-98d2-7c58a641099d.jpg)
![default](https://user-images.githubusercontent.com/29544555/27287424-2b6504ce-5536-11e7-97e0-cf44b8bb8321.jpg)

**Comment by Chandler-Lu** [comment]
先检查一下同样配置的pc端能否使用已确定是否为服务器问题

**Comment by breakwa11** [comment]
你发错地方
