### ISSUE TITLE
4.5.2版的添加服务器订阅有问题

### ISSUE THREAD

**Issue by chenyou-fdu** [shadowsocksr/shadowsocksr-csharp#236]
刚发布的4.5.2版，如果把所有订阅的服务器都删了，再添加服务器订阅就会出现错误

![image](https://user-images.githubusercontent.com/1531217/27383681-a77b05e8-56be-11e7-8e4d-30c4c320e7ce.png)

瞎写一个地址123，点add

![image](https://user-images.githubusercontent.com/1531217/27383691-b1341da4-56be-11e7-8978-77ee9a8fc2f5.png)

结果添加了个默认的，如果我再添加一个地址123

![image](https://user-images.githubusercontent.com/1531217/27383711-c2ad307a-56be-11e7-84b0-3e5b2e555084.png)

就会变成两个一样的

**Comment by breakwa11** [comment]
右边是修改左边选中的，add是复制当前选中的

**Comment by chenyou-fdu** [comment]
哦这样，明白了，谢谢！
但是如果左边只有一个的话，好像还是没法改？（感觉这样的操作逻辑不太顺手哈哈

**Comment by breakwa11** [comment]
@chenyou-fdu 加一个然后删了

**Comment by chenyou-fdu** [comment]
嗯那就这样吧。
