### ISSUE TITLE
4.5.4订阅更新失败

### ISSUE THREAD

**Issue by mzjc** [shadowsocksr/shadowsocksr-csharp#239]
把4.4.6可以正常更新的同一条订阅地址添加到4.5.4却更新失败
另外新的这个订阅设置功能，add一个粘贴进地址后，必须再add第二个，第一个才会正确列到列表里，否则直接确定的话会保存了默认的FreeSSR的订阅地址

**Comment by breakwa11** [comment]
1 你的订阅地址本身格式不正确
2 是BUG

**Comment by mzjc** [comment]
@breakwa11 但在4.4.6下可以正常订阅，仅仅是4.5.4不行，是什么原因呢？是因为订阅地址格式有过更新？4.4.6和4.5.4的订阅地址结构不同？不过我有另一条4.4.6下用的订阅地址，直接复制到4.5.4却依然可以正常更新~所以不知道问题出在哪

**Comment by breakwa11** [comment]
@mzjc 以新版本为准，别跟我说老版本可以

**Comment by mzjc** [comment]
@breakwa11 好的谢谢
