### ISSUE TITLE
杀毒软件报错，请帮助看一下，多谢

### ISSUE THREAD

**Issue by vincentwux** [shadowsocksr/shadowsocksr-csharp#243]
你好，大侠，

4.50,4.54版本ShadowsocksR-dotnet4.0文件Mcafee显示是木马程序，4.55版本ShadowsocksR-dotnet2.0和4.0都显示是木马，目前在使用4.1.4，没有报错，请大侠看一下。

**Comment by ysc3839** [comment]
这个问题你要联系杀毒软件的开发商。

**Comment by Justsoos** [comment]
然而，并没有报：这是4.6.1
http://r.virscan.org/report/cac9719fb7881f26bea8153fa6b76895
4.5.4
http://r.virscan.org/report/96bd49c8e184d927d1c0619481d0d8c3

其他楼主你可以自己试试。真有毒那就是你电脑被感染了。
