### ISSUE TITLE
无法切换服务器？

### ISSUE THREAD

**Issue by basciquant** [shadowsocksr/shadowsocksr-csharp#247]
两台ssr服务器，负载平衡，如果一台宕机了，ssr客户端就一直断线，即使指定到没有宕机的服务器也不行。负载平衡也没用。总之就是无法切换到另一台好的服务器上去。
如果编辑服务器把那个宕机的服务器删除，就好了。

**Comment by breakwa11** [comment]
@basciquant 你能讲清楚吗？负载均衡又不是只有一种模式，你如何操作的指定到另一台服务器？
