### ISSUE TITLE
关于前置代理的问题

### ISSUE THREAD

**Issue by sandianyiyuan** [shadowsocksr/shadowsocksr-csharp#256]
背景：在公司内网需要设置代理才能上外网。公司的有几个内部网站只能直连不能通过设置的代理服务器访问。

现在SSR支持设置前置代理，能实现公司内网使用SSR访问外网以及翻墙，不知道该怎么设置才能实现不通过前置代理访问公司内网呢？

**Comment by breakwa11** [comment]
自己修改代理规则

**Comment by sandianyiyuan** [comment]
已经搞定了。
我将火狐设置为通过SSR上网，SSR再设置前置代理。
谷歌使用系统代理，系统代理设置的公司代理服务器。
这样工作用谷歌，科学上网用火狐
