### ISSUE TITLE
user.rule中存在矛盾规则和可疑规则

### ISSUE THREAD

**Issue by antidemosthenes** [shadowsocksr/shadowsocksr-csharp#259]
版本SSR C# 4.6.1，user.rule文件
1. 以下域名既有remoteproxy又有localproxy：
'.apple.com', '.wsj.com', '.aol.com', '.zaobao.com', '.sina.com', '.sourceforge.net', '.amazon.com', '.w3.org', '.jiepang.com'
2. 存在可疑规则：.help.apple.com localproxy，改规则应该被.apple.com包含，不清楚作者本意
3. .live.com localproxy规则。想使用onedrive的人来说可能没注意这个规则而只加了onedrive.live.com，导致连接失败，改成remoteproxy是不是利大于弊？

**Comment by breakwa11** [comment]
因为我根本没空去检查这个东西对不对，我希望有其它人帮忙维护

**Comment by breakwa11** [comment]
我先添加一个域名规则重复的检查

**Comment by antidemosthenes** [comment]
这种维护起来肯定比gwf，whitelist工程量大得多，个人觉得没必要特别维护和详细管理，提醒用户user.rule文件不完善若出错请自行修改就行了。很多人应该和我一样主要把user.rule当作去广告host处理，因为什么adblock,ublock作用有限。

**Comment by WLZLCX** [comment]
楼上
