### ISSUE TITLE
ssr链接无法使用

### ISSUE THREAD

**Issue by xlovezx** [shadowsocksr/shadowsocksr-csharp#260]
同一链接，他人可正常使用，并且我手机可以正常导入，而电脑上则不行，复制后点击从剪贴版导入无反应，而且从手机上导出的二维码也在电脑上无法识别，出来的的是一个ssr链接和二维码

**Comment by breakwa11** [comment]
@xlovezx 链接格式不规范，c#新版不认

**Comment by xlovezx** [comment]
那如何解决呢@breakwa11

**Comment by xlovezx** [comment]
解决了，统一最新版就ok @breakwa11

**Comment by xlovezx** [comment]
新问题来了，同一 网络环境下，手机可上网，但电脑却显示该网页未发送任何数据，win10，chrome，代理规则为全局，代理模式为全局，且换个别的服务器又能上网，唯独这个不行@breakwa11

**Comment by breakwa11** [comment]
自己检查DNS
