### ISSUE TITLE
为什么新版本剪贴板批量导入ssr地址和那个二维码扫描失效了啊

### ISSUE THREAD

**Issue by swderftg** [shadowsocksr/shadowsocksr-csharp#264]
为什么新版本剪贴板批量导入ssr地址和那个二维码扫描失效了啊，以前版本都可以用的，最近更新了好像没用了。
也把自己电脑上的给删了，重新下载了最新的，还是没用，网上复制了之后，不会自动添加节点了。
然后以前扫描二维码也会自动弹出节点信息，现在只会弹出QR code了。
不知道是大家都有这个问题还是单单我出现这个问题

**Comment by swderftg** [comment]
发现问题了，在更新日志里找到了原因。原来是新版本执行了严格的规范。
“以及严格执行二维码格式规范和订阅格式规范的测试版本
如果你所生成的二维码或SSR链接或订阅格式，无法通过本版本的扫描添加，那么意味着格式有错误，需要及时更新，否则将来所有版本均将无法扫描添加”

**Comment by swderftg** [comment]
退回4.5.0版本可用了

**Comment by WLZLCX** [comment]
4.6.1路过
