### ISSUE TITLE
版本4.6.1剪切板批量导入不能用。

### ISSUE THREAD

**Issue by aaron0713** [shadowsocksr/shadowsocksr-csharp#272]
RT
已确定剪切板中有合法的链接字符串
多个链接串用“|”分隔

**Comment by aaron0713** [comment]
找到原因了，SSR更新了Base64算法，我的运营商提供的老版本Base64密文包含“=”

**Comment by ysc3839** [comment]
https://github.com/breakwa11/shadowsocks-rss/wiki/SSR-QRcode-scheme
> 定义base64为URL safe base64，且不带padding（没有末尾的等于号）

**Comment by aaron0713** [comment]
因为运营商提供的编码还是比较老的，能不能有一个过渡期
先将将base64转换成URL safe base64 然后再解码，转码或者解码失败再抛异常

**Comment by ysc3839** [comment]
我个人觉得过渡期已经够长了。4.5.1 版本开始严格执行规范，而很早的版本就已经支持链接了……

**Comment by aaron0713** [comment]
好吧，我联系一下供应商
