### ISSUE TITLE
windows下ssr4.6.1 蜜汁订阅问题

### ISSUE THREAD

**Issue by qinghuas** [shadowsocksr/shadowsocksr-csharp#279]
环境：windows 10 x64 1703，ssr 4.6.1
能够订阅默认地址，于是我将我的所有ssr://xxx的地址（一行一个）base64加密后，放在服务器上，尝试订阅，失败。研究，将自己的ssr://xxx地址与默认地址解密后取得的ssr://xxx在解密一次，比较，各种配置信息顺序都对，蜜汁尴尬。
判断问题可能在/?obfsparam所传递的混淆参数、服务器节点名称、group问题，于是进行测试：
1.将默认订阅地址的任意一个ssr://xxx链接解密后，将其/?obfsparam后的内容替换成我的ssr://xxx解密后的/?obfsparam，尝试订阅，成功
2.默认订阅地址的ssr://xxx没有混淆参数，取消我的ssr://的混淆参数，订阅，失败。
3.去掉我的服务器名称和group名称的空格，base64加密后替换我的/?obfsparam后的内容，订阅，失败。
3.去掉我的ssr://链接的所有=号，订阅，失败
4.在ios的shadowsocket和android for ssr上尝试订阅未做任何修改的订阅文件，成功。

还有一点不理解，将默认订阅地址任意一条ssr://xxx解密后都能发现：
/?obfsparam=&remarks=6ZmQ6YCf6LSm5Y-3IHZwcyAx&group=RnJlZVNTUi1wdWJsaWM
remarks为服务器名称，base64解密后的内容是：限速账午Ȍ
将6ZmQ6YCf6LSm5Y-3IHZwcyAx的“-”替换为“+”，base64解密后的内容是：限速账号 vps 1
windows for ssr 4.6.1却能够正确识别...

**Comment by friend8179** [comment]
本人也失败,生成的SSR链接和软件生成的对不上

**Comment by ysc3839** [comment]
需要 urlsafe base64

**Comment by qinghuas** [comment]
@ysc3839 谢谢您，已解决问题。

**Comment by qinghuas** [comment]
为每一位ss-panel-v3用户提供一个专属订阅地址：https://github.com/qinghuas/ss-panel-v3-subscription
