### ISSUE TITLE
为啥ShadowsocksR for Windows的code被remove了？

### ISSUE THREAD

**Issue by stevejobschen** [shadowsocksr/shadowsocksr-csharp#288]
如题

**Comment by GoogleGFW** [comment]
并没有。

**Comment by stevejobschen** [comment]
![image](https://user-images.githubusercontent.com/22467932/28550158-b17dee08-7111-11e7-816b-4312069b24a9.png)

**Comment by lizongzeshunshun** [comment]
@stevejobschen branch - master

**Comment by stevejobschen** [comment]
好吧，默认的branch是rm...

**Comment by xjtushilei** [comment]
@lizongzeshunshun   容易暴露
