### ISSUE TITLE
以后有可能可以直接加速游戏吗？

### ISSUE THREAD

**Issue by saladinxp** [shadowsocksr/shadowsocksr-csharp#29]
不用配合其他软件 或者不用配合路由器

**Comment by breakwa11** [comment]
你想太多了

**Comment by loveyanbei** [comment]
讲道理http走流量可以加速的#(滑稽)
如果妹子或者妹子的小伙伴能把socks5转vpn#(滑稽)

**Comment by xbb123** [comment]
试试 SS libev redir

**Comment by saladinxp** [comment]
@xbb123 请问有链接吗，好像没google到

**Comment by xbb123** [comment]
@saladinxp https://github.com/shadowsocks/shadowsocks-libev#openwrt
