### ISSUE TITLE
请问一下shadowsocksR C# 3.8.0.1版是作者开发的吗？

### ISSUE THREAD

**Issue by Kanade666** [shadowsocksr/shadowsocksr-csharp#32]
github上和bittorrent sync上都没有更新这个版本，而且我从别处下载这个版本报毒，比较怀疑。

**Comment by breakwa11** [comment]
请问你下载的版本里面有没有sig后缀的签名文件？你有没有使用GPG去校验一下？里面有没有相应的帮助文档以及templates文件夹？

**Comment by wpf1223** [comment]
@breakwa11 你好，请问3.8.0.1需要在哪里可以下载？另外我在别处下载的提示我有3.8.0.2版本，有sis的签名文件以及templates文件夹。

**Comment by breakwa11** [comment]
@wpf1223 那么请看帮助文档

**Comment by XhstormR** [comment]
@breakwa11 为何 GitHub 上还是 3.7.4.1？？

**Comment by wpf1223** [comment]
帮助文档里面有获取办法，google搜一下

2016年4月30日星期六，XhstormR <notifications@github.com> 写道：

> @breakwa11 <https://github.com/breakwa11> 为何 GitHub 上还是 3.7.4.1？？
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/breakwa11/shadowsocks-csharp/issues/32#issuecomment-215943963>
>


-- 
发自移动版 Gmail

**Comment by ntgeralt** [comment]
同问，为何 GitHub 上还是 3.7.4.1

**Comment by eromoe** [comment]
github 不发源码 ，不太放心，还是喜欢自己build
