### ISSUE TITLE
请问之后有开发Linux可用的客户端的计划吗？

### ISSUE THREAD

**Issue by pcwuyu** [shadowsocksr/shadowsocksr-csharp#39]
用ｑｔ或者ｊａｖａ呢？
现在的ｑｔ５的版本不支持负载均衡

**Comment by breakwa11** [comment]
libev或python都可以

**Comment by pcwuyu** [comment]
我想要负载均衡的功能啊

2016-08-04 19:27 GMT+08:00 破娃酱 <notifications@github.com>:

**Comment by vansnowpea** [comment]
可否提供linux版本？ 多谢。

**Comment by breakwa11** [comment]
@vansnowpea python/libev
