### ISSUE TITLE
现在最新版发布到底在哪里下靠谱？？

### ISSUE THREAD

**Issue by SuperCatss** [shadowsocksr/shadowsocksr-csharp#54]
之前不是zeronet吗？但是刚才去看了下 zeronet 最新的是3.9.62
现在用的版本是4.0.3
但是从软件帮助里面的关于打开 ，页面提示最新是 4.0.2
从wiki日志打开 里面提示最新下载 是4.0.3
逼死强迫症。
来个大佬 给个 具体的 回答好不好啊，我好确定 下手机版。

**Comment by breakwa11** [comment]
在这里

**Comment by SuperCatss** [comment]
shadowsocksr 这个里面还是在   breakwa11  这里面？ @breakwa11

**Comment by breakwa11** [comment]
@SuperCatss 已转移到shadowsocksr里

**Comment by SuperCatss** [comment]
这样啊，但是软件 里面wiki日志，和关于 按钮 连接的地址不统一，你看看，一个连接到这里，一个连接到brakwa11 那里面。。 @breakwa11

**Comment by Noisyfox** [comment]
Fixed via d148a8c
