### ISSUE TITLE
以后这里更新？顺便问个问题：关于多节点切换

### ISSUE THREAD

**Issue by shamashii** [shadowsocksr/shadowsocksr-csharp#55]
clo先驱的版本中如果添加了多个服务器，在右键里有个“高可用”，启用后的效果就是如果请求某链接时，此时服务器故障或不稳定，会切换到其他服务器，浏览器这里的感觉就是卡了几秒，但是最终网页可打开（**或刷新一次，几率低**）。

咱们的R版本貌似只有“负载均衡”功能（一个网页里的内容多个节点加载，速率快），如果上述实例发生，最终网页不可达，**需刷新（甚至几次**，看监视切到别的服务器后）才行。希望改进（或是有类似功能我没找到？）

**Comment by breakwa11** [comment]
@shamashii 负载均衡的方式你设置了什么

**Comment by shamashii** [comment]
![ykooth7p7nj 5t4 js 0ov5](https://cloud.githubusercontent.com/assets/14242157/21575166/1fd1acc0-cf3f-11e6-8f40-bb359a915c45.png)
这里？

**Comment by breakwa11** [comment]
请修改为低错误优先，或低延迟优先

**Comment by breakwa11** [comment]
附带一句，这个窗口下方的超时设置什么的，点一下默认设置

**Comment by shamashii** [comment]
其实这里的选项也都试过，好吧我再长时间观察一下这两个选项。

另，看了咲貌似clo版的高可用，即使无连接时候，也是在自己切换，看log里，且较频繁
不知R版的是什么机制

**Comment by shamashii** [comment]
![gxcwut cn0gd n_8zar4s0](https://cloud.githubusercontent.com/assets/14242157/21575201/09e979a0-cf40-11e6-8b5d-06ba854db19d.png)
超时？目前是这个设置。在用版本3.8.3

**Comment by breakwa11** [comment]
请更新版本，老版本在这里的优化不足

**Comment by shamashii** [comment]
已更新4.0.3在用，观察中，先close罢
