### ISSUE TITLE
关于一次性认证

### ISSUE THREAD

**Issue by Bob-cheng** [shadowsocksr/shadowsocksr-csharp#57]
如果别人的服务端是 ss-libev 开启了一次性认证，那么客户端就只能用ss加一次性验证连接，而不能使用ssr客户端来兼容了。这样使用ssr时要切换服务器的时候有一点麻烦，得换成ss的客户端，请问ssr能否支持一次性认证选项，方便连接相应的ss-libev 服务端？

**Comment by breakwa11** [comment]
你需要看文档，这问题我回答了不知道多少遍了，请在SSR客户端使用 `verify_sha1` 协议连接

**Comment by glzjin** [comment]
协议 verify_sha12017年1月2日 下午1:43，bobcheng <notifications@github.com>写道：如果别人的服务端是 ss-libev 开启了一次性认证，那么客户端就只能用ss加一次性验证连接，而不能使用ssr客户端来兼容了。这样使用ssr时要切换服务器的时候有一点麻烦，得换成ss的服务器，请问ssr能否支持一次性认证选项，方面连接相应的ss-libev 服务端？

**Comment by Bob-cheng** [comment]
抱歉我的原因.....蟹蟹破酱..赵大侠..
