### ISSUE TITLE
希望负载均衡添加同时拨号功能

### ISSUE THREAD

**Issue by gbaoye** [shadowsocksr/shadowsocksr-csharp#60]
同时拨号，自定义拨号数量，优先拨号延迟低的

**Comment by breakwa11** [comment]
你这说的是什么鬼

**Comment by yfdyh000** [comment]
估计指同时发出多个包。一般不必要吧。有重复成功之风险。

**Comment by gbaoye** [comment]
同时保持2个服务器拨号，一个服务器掉线，自动拨号另一个，

**Comment by breakwa11** [comment]
@gbaoye 请先解释清楚“拨号”

**Comment by yfdyh000** [comment]
@gbaoye 架构上做不到吧。SS只是桥，应用程序与远端服务器的连接建立和保持，SS无法中间人介入。
如果是保持SS的TCP连接（心跳连接？），不确定是否有必要，为减少一次RTT？

**Comment by gbaoye** [comment]
我们用一个客户端同时链接两个服务器其中一个掉线并自动补上另一个服务器，无论如何都保持两个服务器同时在线

**Comment by gbaoye** [comment]
我放弃对于"拨号"的解释权

**Comment by breakwa11** [comment]
如果你没法解释清楚你到底想干什么，那就这样吧

**Comment by yfdyh000** [comment]
@gbaoye 负载均衡-每个服务器至少x个连接。然后客户端发起2个或以上的连接，负载均衡优先选择未连接的服务器。按我的理解是这样的，但用途是什么，尽量多的出口IP/连接数？“按次序”就行吧，只是没有低延迟优先的效果。如果你想客户端发起一个连接而SS发起并保持两个，那估计是做不到的。

**Comment by gbaoye** [comment]
我想我的意思是用ssr并行发起两个服务器端的两个链接，两个服务器，两个密码

**Comment by breakwa11** [comment]
那开负载均衡不就好了

**Comment by gbaoye** [comment]
.......谢谢~

2017-01-11 13:23 GMT+08:00 破娃酱 <notifications@github.com>:
