### ISSUE TITLE
希望能添加回auth_sha1协议

### ISSUE THREAD

**Issue by ysj19921026** [shadowsocksr/shadowsocksr-csharp#61]
由于我的ss账户是购买的服务，我发现换用了auth_sha1_v2或者auth_sha1_v4之后，都不能正常使用了，在旧版本里使用auth_sha1时就正常使用，所以请问能不能添加回auth_sha1协议，或者我通过怎样的办法实现使用auth_sha1协议呢？（除了使用旧版本）

**Comment by breakwa11** [comment]
@ysj19921026 协议处直接填写auth_sha1

**Comment by ysj19921026** [comment]
@breakwa11 thank you, that just works.
