### ISSUE TITLE
不能开机启动

### ISSUE THREAD

**Issue by zxj930057911** [shadowsocksr/shadowsocksr-csharp#67]

**Comment by since2004** [comment]
win10 64位 企业版 也无法启动了，之前的版本可以正常启动。参考https://github.com/shadowsocks/shadowsocks-windows/issues/253这个解决方案也不行

**Comment by zxj930057911** [comment]
我看过253，应该不是什么杀毒软件或者管理员运行的原因，4.0.7正常

**Comment by since2004** [comment]
我任何杀毒软件都没有装，一直正常，就4.0.8不行

**Comment by zxj930057911** [comment]
我觉得4.0.9马上就来。。。哈哈哈

**Comment by since2004** [comment]
4.0.8开机启动的问题你解决没有

**Comment by zxj930057911** [comment]
还没有

**Comment by breakwa11** [comment]
我有点想把这个功能删掉，在我可预见的将来里这个功能会带来无数的麻烦

**Comment by zxj930057911** [comment]
代理规则这个与与系统启动冲突？？

**Comment by breakwa11** [comment]
我没这么说过

**Comment by zxj930057911** [comment]
这是ssr的bug还是系统有问题了？？

**Comment by since2004** [comment]
破娃美女，无法开机启动还是麻烦修改吧

**Comment by breakwa11** [comment]
再催我改的话我就删了这功能

**Comment by zxj930057911** [comment]
听见没！！！！数十个个大汉轮流要少女修改，看不下去了，我先笑会儿。。。嘻嘻嘻

**Comment by Lynn-T** [comment]
话说，不是shartup加个lnk就可以开机启了吗

**Comment by dnxbice** [comment]
@zxj930057911 @breakwa11 @since2004 @Lynn-T 
其实可以考虑扔个快捷方式到C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp

**Comment by ysc3839** [comment]
感觉挺奇怪的，旧版本可以添加怎么到了新版本不行了？
