### ISSUE TITLE
破娃，能出个 ssr 程序的详细使用教程吗？

### ISSUE THREAD

**Issue by since2004** [shadowsocksr/shadowsocksr-csharp#70]
用了这么久的 ssr，大部分功能还是不会用，里面的设置项也多，实在是不太明白啥意思。能出个详细的使用教程吗？

**Comment by breakwa11** [comment]
不可以

**Comment by Sak1tama** [comment]
我过年前已经写好了，可是作者任性不让发布没办法╮( ￣ ▽ ￣' )╭

**Comment by breakwa11** [comment]
你发到自己的博客我又不会阻止你，这些文章不是都这么来的么

**Comment by since2004** [comment]
@Sak1tama 哥们，能把你写的 ssr 教程单独发我吗？

**Comment by Sak1tama** [comment]
@since2004 我感觉这里充满恶意，自己说的话无端端被竖倒拇指，真是醉了.....   你看看这个版本吧 https://github.com/shadowsocksr/shadowsocksr-csharp/releases/download/3.7.4.1/ShadowsocksR-win-3.7.4.1.7z   看得懂就行了。。。

**Comment by Sak1tama** [comment]
@since2004 你试试这个版本吧，https://github.com/shadowsocksr/shadowsocksr-csharp/releases/download/3.7.4.1/ShadowsocksR-win-3.7.4.1.7z 这个版本压缩包里有帮助说明

**Comment by Sak1tama** [comment]
这软件越更越奇怪，好像作者受了什么很严重的心理创伤一样，跟一年前的风格完全变了。。。

**Comment by 727023460** [comment]
同求文档    727023460@qq.com

**Comment by breakwa11** [comment]
@727023460 是不是还要写上楼主好人一生平安？对于这种伸手行为，我觉得是不是需要给个严重警告？

**Comment by 727023460** [comment]
回复好快，楼主好人一生平安

**Comment by breakwa11** [comment]
@727023460 我警告的是你，你现在在做伸手党，这里不欢迎，谢谢

**Comment by yunyu2017** [comment]
同求文档🙃，vps很快就配置完了，然而pc端折腾了半宿还连不上。开始提示端口被占用，换端口后又无网，明明都选了全局，代理端口也改了，就是连不上💔，黑眼圈都粗来了🌚之前用sockscap64挂ss，还能给应用单独代理，然而她并木有ssr的协议插件跟混淆插件😂
