### ISSUE TITLE
可以把托盘图标恢复成白色么？

### ISSUE THREAD

**Issue by iamapig120** [shadowsocksr/shadowsocksr-csharp#71]
win10用户甚至想要卸载……

**Comment by breakwa11** [comment]
你可以看更新说明自定义个图标么

**Comment by iamapig120** [comment]
抱歉抱歉OTZ……
万年就用基础功能所以没注意到

**Comment by breakwa11** [comment]
![image](https://cloud.githubusercontent.com/assets/8436963/22143704/e979c2aa-df35-11e6-94b7-f187bfacad9e.png)

**Comment by iamapig120** [comment]
我果然是瞎了OTZ
