### ISSUE TITLE
建议DNS选项使用冒号":"分隔端口号

### ISSUE THREAD

**Issue by ysc3839** [shadowsocksr/shadowsocksr-csharp#72]
这么做更符合习惯

[DnsQuery.cs#L84](https://github.com/shadowsocksr/shadowsocksr-csharp/blob/ee93449493b525afb480708adfb3128acd2a8d96/shadowsocks-csharp/3rd/opendns/DnsQuery.cs#L84)
把`Server.Split(new char[] { ' ' }, 2)` 改为 `Server.Split(new char[] { ':' }, 2)` 即可支持

**Comment by breakwa11** [comment]
@ysc3839 你应该考虑一下DNS是IPv6的情况

**Comment by ysc3839** [comment]
谢谢，明白了
