### ISSUE TITLE
局域网代理设置好后无效手机端无法代理

### ISSUE THREAD

**Issue by BreakApple** [shadowsocksr/shadowsocksr-csharp#75]
SSR4.0.8 用了FS加速器 加速器版本1.2, SSR开启局域网代理了 雪天代理模式在PAC模式和全局模式下 手机局域网端都无法代理 YouTube等都打不开 确认 地址无误 输入无误 代理地址 http://192.168.1.51:1080/PAC 端口也正确 确认在同一局域网下操作！

**Comment by breakwa11** [comment]
PAC地址不是这个，你必须从客户端的PAC菜单里面复制出来，里面包含一个auth字段

**Comment by breakwa11** [comment]
另外不建议使用PAC，不同环境支持程度不一样，效果也各不相同

**Comment by BreakApple** [comment]
我就是按照网上的教程弄得那应该怎么弄手机能有电脑的FS加速效果就好了！

**Comment by BreakApple** [comment]
主要是以前我就这么设置可以实现代理并有加速效果

**Comment by breakwa11** [comment]
能不能别让我重复一次，我说，PAC地址改了，你要么用改了后的地址，要么不要用PAC直接用代理地址，OK？

**Comment by BreakApple** [comment]
你说的意思是我需要把手机HTTP代理的PAC改成 那个字段 那个字段在哪能找到！

**Comment by BreakApple** [comment]
http://127.0.0.1:1080/pac?auth=BlZbChO6SFva6koatpwk&t=201701210101337739

**Comment by BreakApple** [comment]
这样子对吧

**Comment by BreakApple** [comment]
http://192.168.1.51:1080/BlZbChO6SFva6koatpwk&t=201701210101337739 还是这样

**Comment by BreakApple** [comment]
真的不太会用 能说一下么 这个PAC要怎么改

**Comment by BreakApple** [comment]
突然好了谢谢了
