### ISSUE TITLE
为啥取消二维码功能啊?

### ISSUE THREAD

**Issue by franqi** [shadowsocksr/shadowsocksr-csharp#78]
刚开始放上去的时候确实觉得不明所以,但是后来用到的时候觉得也还是蛮方便了,现在开始喜欢这个功能了,又去掉了,不知道为啥.

喜欢这个功能的在下面点赞或留言,看看有多少人想要保留这个功能的.

**Comment by lizongzeshunshun** [comment]
并没有取消啊。。

**Comment by wenliyang** [comment]
发issue前请先看清楚是不是走错地方了

**Comment by breakwa11** [comment]
> 喜欢这个功能的在下面点赞或留言,看看有多少人想要保留这个功能的

你当这里是微博还是微信？

**Comment by franqi** [comment]
默认是直接显示的吧,现在改成了点ssr链接才能看到,我以为取消了,

**Comment by YangHong2** [comment]
二维码确实挺方便的，个人已经喜欢上了。不想被取消
