### ISSUE TITLE
Remote Address IP很多都没法127.0.0.1，导致优酷等网站还是被运营商劫持

### ISSUE THREAD

**Issue by 1265578519** [shadowsocksr/shadowsocksr-csharp#82]
测试URL：http://v.youku.com/v_show/id_XMjQ4ODk5MjA5Mg==.html
4.1.0最新版全局模式，系统windows 10企业版X64
F12谷歌浏览器抓下包看看就知道了，全局模式，我知道这是调用系统代理的，但是用小飞机能有什么解决方法么，以前也发过一份问题。
https://github.com/shadowsocksr/shadowsocksr-csharp/issues/80

**Comment by breakwa11** [comment]
我去，什么叫做F12抓下包看看就知道？我这又不出发生这个问题我怎么知道？你能不能不要同一个问题发两个地方？警告你

**Comment by 1265578519** [comment]
666
