### ISSUE TITLE
“不使用代理直连”和“不修改IE代理”这两项，建议去掉一个，完全是冗余的功能，还容易出现图标暗了，代理还没关闭的情况

### ISSUE THREAD

**Issue by fuckourselves** [shadowsocksr/shadowsocksr-csharp#84]
4.1.0，“系统代理模式”这个菜单栏，不明白为何要加上“不使用代理直连”的选项，原来“不修改IE代理”就是直连的意思了，现在用这一项代替了不修改IE，导致现在选中不修改IE时，原来的代理并没有清除掉，而此时图标也变暗了，然而代理还是存在着。

“不使用代理直连”和“不修改IE代理”这两项，建议去掉一个，完全是冗余的功能，还容易出现图标暗了，代理还没关闭的情况

**Comment by breakwa11** [comment]
@fuckourselves 现在的不修改，就是不修改，不是直连，直连就找修改为直连

**Comment by fuckourselves** [comment]
@breakwa11 这有什么意义呢？这个不修改，不就是为了直连吗？现在图标灭了还开着代理，想想都很不稳妥，流量就这么不知不觉中没了

**Comment by breakwa11** [comment]
@fuckourselves 不修改就是不修改，和直连没有任何关系，麻烦自己想清楚

**Comment by yfdyh000** [comment]
@fuckourselves 不修改是：IE设为直连或其他代理都不管。
不使用代理直连是：修改代理为SS，但SS收到后直接通过系统接口转发出去，不走代理渠道。
以上未经测试和确认，仅为字面所得。

**Comment by ysc3839** [comment]
@fuckourselves 这个功能是防止覆盖掉代理设置。比如我用Fiddler设置了代理，这时候打开SSR的话就会覆盖掉设置，如果选了不修改那就不会覆盖了。

**Comment by Sak1tama** [comment]
也许这软件有些设置的中文用词可以人性化一些，小白不一定看得懂这些词语。。。可是某人无脑的给一个倒拇指，还有作者目空一切的心态，我无语了。。。。
