### ISSUE TITLE
又一个奇怪的逻辑问题，选择系统代理会影响python的代理！而且逻辑乱了

### ISSUE THREAD

**Issue by Justsoos** [shadowsocksr/shadowsocksr-csharp#85]
默认的【不修改系统（IE）代理】看似没问题，今天竟然发现逻辑非常乱：

1，如果是开机就启动SSR-Csharp dotnet4.0.exe，【不修改系统（IE）代理】这个点选，则有机会让win10系统安装的python 执行的程序，有几率走代理，也有几率不走代理。
2，如果首先选择【全局代理】，再回到【不修改系统（IE）代理】，则几率很大会走代理（差不多100%）。
3，如果首先选择【不经过代理直连】，再回到【不修改系统（IE）代理】，则有很大几率直连（差不多100%）。

用win10系统自带的 cmd，自己装的 cmder 测试，得到如上同样的结果。但win10 下安装的**mingw64 不受代理与否影响，一直是直连状态！**

另外，问一下，让python 走代理，怎么做到的？ 好神奇啊。同时测了ss 最新客户端，没有这个问题。

**Comment by Justsoos** [comment]
没开代理，竟然能用youtube-dl（python）看youtube，吓我一跳。才发现被上了代理。

在【不修改系统（IE）代理】的状态

**Comment by Justsoos** [comment]
补充：又测到win10 power shell 也在影响此列。

**Comment by breakwa11** [comment]
我服了，首先你就没理解什么是"不修改"，这样反馈的信息几乎都是没什么用的，本来就确实是这样

**Comment by inkydragon** [comment]
@Justsoos 不修改系统（IE）代理 !==  不使用代理

**Comment by ysc3839** [comment]
Python程序一般是读取环境变量(如 `http_proxy` `https_proxy`)，建议你检查一下

**Comment by Justsoos** [comment]
@ysc3839   http_proxy https_proxy 这两个变量根本没有。看来是win10 特别为终端准备的套餐。power shell 也能用代理了！！

**Comment by Justsoos** [comment]
@breakwa11  @inkydragon  算了，不是什么大bug，但的确是逻辑有问题的。
和那个编辑了服务器，再保存，一会儿会激活，一会儿不会激活的逻辑一样，让人有点摸不着头脑。

**Comment by yfdyh000** [comment]
@Justsoos 代码在 https://github.com/shadowsocksr/shadowsocksr-csharp/blob/master/shadowsocks-csharp/Controller/SystemProxy.cs ，建议在代码层面指出。
不知道你的 Python 程序怎么获取的代理设置。如果你的系统有设置其他代理，而你选择不修改，有可能代理设置存在，并且 Python 程序通过某些渠道检测或采用了。
你的各项选择后，有重新启动 Python 程序吗，确保环境变量和代理设置的检测/获取被重新执行。

**Comment by Justsoos** [comment]
@yfdyh000  我一方面是惊奇，废了好多劲，给python 程序找代理的办法，没找到，突然win10 + ss 偶然之下就给代劳了。而且还是 SSR 的菜单和功能逻辑混乱带来的。。。。
偶然发现。很显然不是设置 ie pac那么简单的代理，而是系统底层，win10 搞得。 我也在找底层接口，不过还没找到。google 也没见谁说这个。
目前发现，我的python 程序在SS和SSR 设置了系统翻墙代理情况下，直接可以翻墙，不用做任何设置。

**Comment by breakwa11** [comment]
@Justsoos 之所以我这么怕小白，还刻意写了说明，就是因为小白把自己的混乱归因于软件

**Comment by Justsoos** [comment]
> @breakwa11 我服了，首先你就没理解什么是"不修改"，这样反馈的信息几乎都是没什么用的，本来就确实是这样

还真不是我不理解，而是SSR里面发现两个地方的设置有【结果】的二义性。呵呵，只不过我这个描述复杂了些，信息太庞杂了。而这些设置，在SS里都没有二义性的啊。

**Comment by Justsoos** [comment]
@breakwa11  破墙娃，你为啥不去研究核心算法优化神马的 -- 我刚看了你纠正OTA等一系列网文介绍 -- 却跑来这里随时解答界面这些前端编程？？你的时间和精力安排，好浪费啊。谈个男朋友也好啊，哈～

**Comment by ysc3839** [comment]
@Justsoos 我不认为和底层有关。如果是的话，那么SSR也会走代理，就死循环了。

**Comment by falseen** [comment]
虽然我没测试过win10是否真的会这样，但我觉得这是有可能的，这不是ss的问题，而是系统的问题。我之前用Fiddler的时候不知道修改了什么东西，它竟然让python也通过它了，当时用的系统是xp。

**Comment by ysc3839** [comment]
Fiddler只会修改IE代理，如果Python走的话说明那个程序读取了IE的代理设置
