### ISSUE TITLE
会加入对gcm加密的支持吗？

### ISSUE THREAD

**Issue by anadano** [shadowsocksr/shadowsocksr-csharp#90]
其实我想问问会不会支持libev版弄的新的aes-xxx-gcm加密，我在电脑上不管服务端是ss还是ssr都是用这个客户端的
ps:截至现在2017.2.15，shadowsocks windows并未支持gcm加密方式，shadowsocks Android已支持，其他的我没办法测试

**Comment by anadano** [comment]
好像应该叫AEAD算法，具体协议应该有
AES-128-GCM
AES-192-GCM
AES-256-GCM
ChaCha20-IETF-Poly1305
XChaCha20-IETF-Poly1305

**Comment by breakwa11** [comment]
除非shadowsocks windows支持了我再考虑

**Comment by Dwscdv3** [comment]
@breakwa11 shadowsocks-windows 已经在三个月前支持AEAD了，这边有加入支持的打算吗？
