### ISSUE TITLE
wingy扫描二维码添加路线提示备注为空？

### ISSUE THREAD

**Issue by 467600474** [shadowsocksr/shadowsocksr-csharp#92]
wingy扫描二维码添加路线提示备注为空？wingy扫描二维码添加路线提示备注为空？ 备注我写了但还是这样。

**Comment by KISSMonX** [comment]
额。。。跟我刚发的#91是一个问题。

**Comment by 467600474** [comment]
我发完才注意到

**Comment by breakwa11** [comment]
扫的什么二维码你没说，你到底扫描什么我还是不知道，备注为空什么的你怎么不先问wingy，问我干嘛

**Comment by 467600474** [comment]
扫描ssr连接二维码

**Comment by breakwa11** [comment]
@467600474 我去，多说一点不行吗

**Comment by 467600474** [comment]
在wingy通过扫描二维码增加线路，扫描ss连接二维码，提示配置无效，扫描ssr连接二维码提示备注为空。我在问wingy那边所以上面就写的简单了一点

**Comment by breakwa11** [comment]
@467600474 。。。。拜托，你到底是扫哪里的码啊

**Comment by 467600474** [comment]
ShadowsocksR-dotnet4.0编辑服务器页面的二维码

**Comment by breakwa11** [comment]
@467600474 这个二维码是标准格式，如有任何问题问扫这个码的APP

**Comment by 467600474** [comment]
恩

**Comment by KISSMonX** [comment]
我用wingy扫毛也提示错误, 微信扫描内容为空. 支付宝可以扫描到内容.

**Comment by 467600474** [comment]
ios上还有什么还用的其他软件吗？

**Comment by elespec** [comment]
最初的时候我以为是楼主的二维码问题,因为再ss提供商可以扫描进去,然后我发现,是因为wingy支持ssr的混淆方式,wingy免费版本直接不提示,收费版本会有一个提示,所以,,,,使用wingy的...按照ss服务信息,手写导入就行,但混淆就没戏了;

**Comment by elespec** [comment]
好像还有一个叫LIFI的;

**Comment by 467600474** [comment]
收费的
