### ISSUE TITLE
请问怎么快速添加服务器？

### ISSUE THREAD

**Issue by lisso** [shadowsocksr/shadowsocksr-csharp#93]
扫描二维码只是出现一个 ssr://地址 和 二维码图片 的窗口。
剪切板批量导入ssr://地址 点了没有反应，编辑服务器时 ssr链接 也不能编辑
添加服务器只能手动填写每一项吗？

**Comment by ysc3839** [comment]
我猜测点了没反应可能是链接有问题

**Comment by breakwa11** [comment]
@lisso 说明链接有问题

**Comment by lisso** [comment]
确实是链接有问题
