### ISSUE TITLE
SSR C#4.1.1和adbyby、阿呆喵有冲突

### ISSUE THREAD

**Issue by jjhhoo** [shadowsocksr/shadowsocksr-csharp#95]
你好，我因为不太喜欢广告，所以一直在用老版本的adbyby这个去广告软件。
今天，我更新了新版的adbyby，结果发现两个一起用翻墙失效了，再试了另一个阿呆喵最新结果也不能翻墙。
之前换用SSR的时候，还没把原版SS给删了。试了下原版，去广告正常，翻墙也正常。
SSR一直以GFWLIST PAC运行。
小白冒昧发个反馈，我也会去这两个软件那里反馈下问题的。

**Comment by w153140** [comment]
为啥不直接用浏览器插件去广告，而用软件。。。

**Comment by EMLVIRUS** [comment]
@w153140 因为能过滤其它产生HTTP(S)流量软件的广告

**Comment by alexromance** [comment]
推荐你用adground ，非常强大，chrome也有插件版，也有软件版值得一试
