### ISSUE TITLE
换服务器真麻烦!

### ISSUE THREAD

**Issue by sxml** [shadowsocksr/shadowsocksr-csharp#96]
就不能第一级 显示选择? 从A换B 需要点开那么多

![5](https://cloud.githubusercontent.com/assets/4932232/23162061/82f27a04-f867-11e6-97ad-fe5dcfa89494.jpg)

**Comment by breakwa11** [comment]
建议用服务器统计窗口来切换

**Comment by sxml** [comment]
经常需要换 有点麻烦 
双击弹出的编辑器 不能换服务器连接?
统计窗口 若是关闭 还得几步点开

![6](https://cloud.githubusercontent.com/assets/4932232/23162263/3ee6c760-f868-11e6-9533-4e29b24f0f69.jpg)

**Comment by yfdyh000** [comment]
中键点托盘图标打开统计窗口。

再次建议：允许从统计窗口打开编辑窗口（通过菜单栏/右键菜单），并将中键/双击托盘图标的操作互换。

**Comment by breakwa11** [comment]
@yfdyh000 请双击对应服务器ID来编辑对应的节点，这个功能去年就做好了

**Comment by sxml** [comment]
@yfdyh000 呵呵 都不知道有 中键 这个方便 就是中键不习惯用

**Comment by sxml** [comment]
建议 将中键/双击托盘图标的操作互换。

**Comment by yfdyh000** [comment]
@breakwa11 还不错，但双击会导致服务器切换，而且单击切换、双击打开的操作比较怪。既然有菜单栏，应该用上。

**Comment by breakwa11** [comment]
@yfdyh000 只要你不点服务器名字列表是不会切换的，双击ID的地方我说的是
@sxml 由于操作习惯问题，现在不方便换
