### ISSUE TITLE
代理规则无法区分国内外流量

### ISSUE THREAD

**Issue by suitrue** [shadowsocksr/shadowsocksr-csharp#97]
我用最新的4.1.1版本，
在代理规则中选择Bypass Lan & China ，所有流量都经过代理，国内网站也走代理；
选择Bypass Lan & no China,则所有流量都不经过代理，Google无法访问。
bypass lan是可以成功的，但软件似乎把国内流量也当做国外流量了。
折腾了半天，全局代理用ie也试过了，chrome代理插件也用过了，都是一样的问题，不知道怎么解决。

**Comment by breakwa11** [comment]
你没有保留delegated-apnic.txt

**Comment by suitrue** [comment]
确实是这样 感谢回复
