### ISSUE TITLE
请问如何在不关闭软件的情况下断开SSR

### ISSUE THREAD

**Issue by w153140** [shadowsocksr/shadowsocksr-csharp#98]
SS他可以断开，但是SSR好像找不到。
![qq 20170224144810](https://cloud.githubusercontent.com/assets/24273319/23293331/82095d16-faa0-11e6-9e49-9ceb8524a0f3.jpg)

**Comment by breakwa11** [comment]
SS也不可以断开

**Comment by yfdyh000** [comment]
@w153140 服务器-断开当前所有连接？

**Comment by w153140** [comment]
@breakwa11 可以啊
![qq 20170224205523](https://cloud.githubusercontent.com/assets/24273319/23304271/e3e0cdf2-fad3-11e6-9d25-24554c41d3c6.jpg)

**Comment by breakwa11** [comment]
@w153140 这根本就不是断开的意思，即使这样你一样能用代理，别没经过测试就问我这种是你自己理解错误的问题
