### ISSUE TITLE
PC版本如何UDP转发

### ISSUE THREAD

**Issue by tang1989324** [shadowsocksr/shadowsocksr-csharp#99]
请问下哪里设置的

**Comment by ysc3839** [comment]
应该是不需要设置的

**Comment by THaGKI9** [comment]
需要填 UDP 端口，UDP 端口指的是 ssr 服务器的 UDP 端口

**Comment by tang1989324** [comment]
@THaGKI9 直接再服务器高级选项里勾选 UDP端口天SSR端口？ UDP over TCP也要打钩？

**Comment by THaGKI9** [comment]
勾选 UDP，填入服务器 UDP 端口
至于 UDP over TCP 打勾打不打，看你自己，一般不打

Sent from my iPhone

On 2 Mar 2017, at 10:43, tang1989324 <notifications@github.com<mailto:notifications@github.com>> wrote:


@THaGKI9<https://github.com/THaGKI9> 直接再服务器高级选项里勾选 UDP端口天SSR端口？ UDP over TCP也要打钩？

**Comment by tang1989324** [comment]
@THaGKI9 感谢，UDP端口就是给的账号端口吧

**Comment by THaGKI9** [comment]
@tang1989324 是的

**Comment by breakwa11** [comment]
UDP端口写0表示使用和TCP一样的端口，默认并不需要修改

**Comment by Portan** [comment]
@tang1989324 说明里面这么写的，
For UDP, you need to use SocksCap or ProxyCap to force programs you want to proxy to tunnel over ShadowsocksR
所以可能需要SocksCap or ProxyCap程序

**Comment by sinderyminami** [comment]
udp port也可以填和服务端端口不一样的 翻以前的更新记录里有一条说明过
